import type { SectionSchema } from "./types";

export const COMMON_SCHEMAS: SectionSchema[] = [
  {
    file: "common",
    section: "navbar",
    title: "Üst Menü",
    description: "Sitenin üst kısmındaki menü yazıları",
    fields: [
      { path: "solutions", label: "Çözümler", type: "text" },
      { path: "solutionsDesc", label: "Çözümler açıklaması", type: "text" },
      { path: "products", label: "Ürünler", type: "text" },
      { path: "productsDesc", label: "Ürünler açıklaması", type: "text" },
      { path: "services", label: "Hizmetler", type: "text" },
      { path: "servicesDesc", label: "Hizmetler açıklaması", type: "text" },
      { path: "technicalCenter", label: "Teknik Merkez", type: "text" },
      { path: "technicalCenterDesc", label: "Teknik Merkez açıklaması", type: "text" },
      { path: "corporate", label: "Kurumsal", type: "text" },
      { path: "corporateDesc", label: "Kurumsal açıklaması", type: "text" },
      { path: "contact", label: "İletişim", type: "text" },
      { path: "contactDesc", label: "İletişim açıklaması", type: "text" },
      { path: "fanSelector", label: "Fan Seçici butonu", type: "text" },
      { path: "viewAll", label: "Tümünü Gör", type: "text" },
      { path: "featured", label: "Öne Çıkan", type: "text" },
      { path: "openMenu", label: "Menü açma yazısı", type: "text", advancedOnly: true },
    ],
  },
  {
    file: "common",
    section: "footer",
    title: "Alt Bilgi (Footer)",
    description: "Sitenin alt kısmındaki yazılar",
    fields: [
      { path: "ctaTitle", label: "Üst çağrı başlığı", type: "text" },
      { path: "ctaDesc", label: "Üst çağrı açıklaması", type: "textarea", rows: 2 },
      { path: "ctaButton", label: "Üst çağrı butonu", type: "text" },
      { path: "brandDesc", label: "Marka açıklaması", type: "textarea", rows: 3 },
      { path: "copyright", label: "Telif hakkı yazısı", type: "text" },
      { path: "cookieSettings", label: "Çerez ayarları", type: "text" },
      { path: "kvkk", label: "KVKK linki", type: "text" },
      { path: "privacyPolicy", label: "Gizlilik politikası", type: "text" },
      { path: "sections.products", label: "Ürünler başlığı", type: "text" },
      { path: "sections.solutions", label: "Çözümler başlığı", type: "text" },
      { path: "sections.corporate", label: "Kurumsal başlığı", type: "text" },
      { path: "sections.services", label: "Hizmetler başlığı", type: "text" },
    ],
  },
];
