import type { SectionSchema } from "./types";

export const CONTACT_SCHEMAS: SectionSchema[] = [
  {
    file: "contact",
    section: "main",
    title: "İletişim Sayfası",
    description: "İletişim formu ve adres bilgileri",
    fields: [
      { path: "badge", label: "Üst etiket", type: "text" },
      { path: "heroTitle1", label: "Başlık satır 1", type: "text" },
      { path: "heroTitle2", label: "Başlık satır 2", type: "text" },
      { path: "heroTitle3", label: "Başlık satır 3", type: "text" },
      { path: "heroDesc", label: "Açıklama", type: "textarea", rows: 3 },
      { path: "headOffice", label: "Merkez ofis başlığı", type: "text" },
      { path: "headOfficeAddress", label: "Merkez ofis adresi", type: "textarea", rows: 4 },
      { path: "factory", label: "Fabrika başlığı", type: "text" },
      { path: "factoryAddress", label: "Fabrika adresi", type: "textarea", rows: 4 },
      { path: "workingHours", label: "Çalışma saatleri başlığı", type: "text" },
      { path: "weekdays", label: "Hafta içi", type: "text" },
      { path: "saturday", label: "Cumartesi", type: "text" },
      { path: "sunday", label: "Pazar", type: "text" },
      { path: "closed", label: "Kapalı yazısı", type: "text" },
      { path: "formTitle", label: "Form başlığı", type: "text" },
      { path: "formDesc", label: "Form açıklaması", type: "text" },
      { path: "successMessage", label: "Başarı mesajı", type: "textarea", rows: 2 },
      { path: "labelName", label: "Ad Soyad etiketi", type: "text" },
      { path: "labelCompany", label: "Firma etiketi", type: "text" },
      { path: "labelPhone", label: "Telefon etiketi", type: "text" },
      { path: "labelEmail", label: "E-posta etiketi", type: "text" },
      { path: "labelDepartment", label: "Birim etiketi", type: "text" },
      { path: "labelSubject", label: "Konu etiketi", type: "text" },
      { path: "labelMessage", label: "Mesaj etiketi", type: "text" },
      { path: "send", label: "Gönder butonu", type: "text" },
      { path: "kvkkConsent", label: "KVKK onay metni", type: "textarea", rows: 3 },
      { path: "mapTitle", label: "Harita başlığı", type: "text" },
      { path: "mapSubtitle", label: "Harita alt başlığı", type: "text" },
      { path: "openInMap", label: "Haritada aç butonu", type: "text" },
    ],
  },
];
