import type { SectionSchema } from "./types";

export const CONTACT_SCHEMAS: SectionSchema[] = [
  {
    file: "contact",
    section: "main",
    title: "?leti?im Sayfas?",
    description: "?leti?im formu ve adres bilgileri",
    fields: [
      { path: "badge", label: "Üst etiket", type: "text" },
      { path: "heroTitle1", label: "Ba?l?k sat?r 1", type: "text" },
      { path: "heroTitle2", label: "Ba?l?k sat?r 2", type: "text" },
      { path: "heroTitle3", label: "Ba?l?k sat?r 3", type: "text" },
      { path: "heroDesc", label: "Aç?klama", type: "textarea", rows: 3 },
      { path: "headOffice", label: "Merkez ofis ba?l???", type: "text" },
      { path: "headOfficeAddress", label: "Merkez ofis adresi", type: "textarea", rows: 4 },
      { path: "factory", label: "Fabrika ba?l???", type: "text" },
      { path: "factoryAddress", label: "Fabrika adresi", type: "textarea", rows: 4 },
      { path: "workingHours", label: "Çal??ma saatleri ba?l???", type: "text" },
      { path: "weekdays", label: "Hafta içi", type: "text" },
      { path: "saturday", label: "Cumartesi", type: "text" },
      { path: "sunday", label: "Pazar", type: "text" },
      { path: "closed", label: "Kapal? yaz?s?", type: "text" },
      { path: "formTitle", label: "Form ba?l???", type: "text" },
      { path: "formDesc", label: "Form aç?klamas?", type: "text" },
      { path: "successMessage", label: "Ba?ar? mesaj?", type: "textarea", rows: 2 },
      { path: "labelName", label: "Ad Soyad etiketi", type: "text" },
      { path: "labelCompany", label: "Firma etiketi", type: "text" },
      { path: "labelPhone", label: "Telefon etiketi", type: "text" },
      { path: "labelEmail", label: "E-posta etiketi", type: "text" },
      { path: "labelDepartment", label: "Birim etiketi", type: "text" },
      { path: "labelSubject", label: "Konu etiketi", type: "text" },
      { path: "labelMessage", label: "Mesaj etiketi", type: "text" },
      { path: "send", label: "Gönder butonu", type: "text" },
      { path: "kvkkConsent", label: "KVKK onay metni", type: "textarea", rows: 3 },
      { path: "mapTitle", label: "Harita ba?l???", type: "text" },
      { path: "mapSubtitle", label: "Harita alt ba?l???", type: "text" },
      { path: "openInMap", label: "Haritada aç butonu", type: "text" },
    ],
  },
];
