import type { SectionSchema } from "./types";

export const HOME_SCHEMAS: SectionSchema[] = [
  {
    file: "home",
    section: "hero",
    title: "Ana Sayfa — Büyük Başlık",
    description: "Ziyaretçilerin ilk gördüğü büyük yazılar, video ve istatistikler",
    fields: [
      { path: "badge", label: "Üst rozet yazısı", type: "text", help: "Başlığın üstündeki küçük etiket" },
      { path: "eyebrow", label: "Üst satır", type: "textarea", rows: 2 },
      { path: "heroLabel", label: "Ürün etiketi", type: "text" },
      { path: "titleLine1", label: "Başlık satır 1", type: "text" },
      { path: "titleLine2", label: "Başlık satır 2", type: "text" },
      { path: "titleLine3", label: "Başlık satır 3", type: "text" },
      { path: "subtitle", label: "Alt açıklama", type: "textarea", rows: 3 },
      { path: "ctaPrimary", label: "Ana buton yazısı", type: "text" },
      { path: "ctaSecondary", label: "İkinci buton yazısı", type: "text" },
      { path: "videoSrc", label: "Hero video yolu", type: "text", help: "Örn: /video/hero-scroll-sand.mp4" },
      { path: "mobileHeroImage", label: "Mobil hero görseli", type: "image" },
      { path: "heroImageAlt", label: "Görsel açıklaması", type: "text" },
      {
        path: "stats",
        label: "İstatistikler",
        type: "list",
        listLabel: "İstatistik",
        itemFields: [
          { path: "value", label: "Sayı", type: "text" },
          { path: "label", label: "Açıklama", type: "text" },
        ],
      },
      { path: "endCard.series", label: "Kart — seri adı", type: "text" },
      { path: "endCard.title", label: "Kart — başlık", type: "text" },
      { path: "endCard.desc", label: "Kart — açıklama", type: "textarea", rows: 3 },
      { path: "endCard.cta", label: "Kart — buton yazısı", type: "text" },
      { path: "endCard.spec1Label", label: "Özellik 1 etiketi", type: "text" },
      { path: "endCard.spec1Value", label: "Özellik 1 değeri", type: "text" },
      { path: "endCard.spec2Label", label: "Özellik 2 etiketi", type: "text" },
      { path: "endCard.spec2Value", label: "Özellik 2 değeri", type: "text" },
      { path: "endCard.spec3Label", label: "Özellik 3 etiketi", type: "text" },
      { path: "endCard.spec3Value", label: "Özellik 3 değeri", type: "text" },
    ],
  },
  {
    file: "home",
    section: "animation2",
    title: "Scroll Video — Bitiş Kartı",
    description: "Hero scroll videosunun sonundaki ürün kartı",
    fields: [
      { path: "startCard.badge", label: "Başlangıç — rozet", type: "text" },
      { path: "startCard.titleLine1", label: "Başlangıç — başlık 1", type: "text" },
      { path: "startCard.titleLine2", label: "Başlangıç — başlık 2", type: "text" },
      { path: "startCard.titleLine3", label: "Başlangıç — başlık 3", type: "text" },
      { path: "startCard.subtitle", label: "Başlangıç — açıklama", type: "textarea", rows: 3 },
      { path: "endCard.series", label: "Bitiş — seri", type: "text" },
      { path: "endCard.title", label: "Bitiş — başlık", type: "text" },
      { path: "endCard.desc", label: "Bitiş — açıklama", type: "textarea", rows: 4 },
      { path: "endCard.cta", label: "Bitiş — buton", type: "text" },
      { path: "endCard.spec1Label", label: "Özellik 1 etiketi", type: "text" },
      { path: "endCard.spec1Value", label: "Özellik 1 değeri", type: "text" },
      { path: "endCard.spec2Label", label: "Özellik 2 etiketi", type: "text" },
      { path: "endCard.spec2Value", label: "Özellik 2 değeri", type: "text" },
      { path: "endCard.spec3Label", label: "Özellik 3 etiketi", type: "text" },
      { path: "endCard.spec3Value", label: "Özellik 3 değeri", type: "text" },
    ],
  },
  {
    file: "home",
    section: "video",
    title: "Kurumsal Video Bölümü",
    fields: [
      { path: "tag", label: "Üst etiket", type: "text" },
      { path: "title", label: "Başlık", type: "text" },
      { path: "desc", label: "Açıklama", type: "textarea", rows: 3 },
      { path: "aboutUs", label: "Biz Kimiz butonu", type: "text" },
      { path: "references", label: "Referanslar butonu", type: "text" },
      { path: "iframeTitle", label: "Video erişilebilirlik", type: "text", advancedOnly: true },
    ],
  },
  {
    file: "home",
    section: "engineeringShowcase",
    title: "Mühendislik Vitrini",
    fields: [
      { path: "title", label: "Başlık", type: "text" },
      { path: "subtitle", label: "Alt başlık", type: "text" },
      { path: "body", label: "Metin", type: "textarea", rows: 5 },
      { path: "cta", label: "Buton yazısı", type: "text" },
      { path: "image1", label: "Görsel 1", type: "image", advancedOnly: true },
      { path: "image2", label: "Görsel 2", type: "image", advancedOnly: true },
    ],
  },
  {
    file: "home",
    section: "midCta",
    title: "Orta Çağrı",
    fields: [
      { path: "title", label: "Başlık", type: "text" },
      { path: "desc", label: "Açıklama", type: "textarea", rows: 3 },
      { path: "button", label: "Buton yazısı", type: "text" },
    ],
  },
  {
    file: "home",
    section: "pillars",
    rootIsArray: true,
    title: "3 Sütun Bölümü",
    description: "Ana sayfadaki 3 sütunlu tanıtım kartları",
    fields: [
      {
        path: "",
        label: "Sütunlar",
        type: "list",
        listLabel: "Sütun",
        itemFields: [
          { path: "tag", label: "Etiket", type: "text" },
          { path: "title", label: "Başlık", type: "text" },
          { path: "intro", label: "Giriş metni", type: "textarea", rows: 4 },
          { path: "cta", label: "Buton yazısı", type: "text" },
          { path: "icon", label: "Kart ikonu", type: "icon" },
          { path: "iconImage", label: "Özel ikon görseli", type: "image" },
          { path: "image", label: "Kart görseli", type: "image" },
          { path: "videoSrc", label: "Video yolu (opsiyonel)", type: "text", help: "Doluysa görsel yerine video oynar" },
          { path: "videoPoster", label: "Video kapak görseli", type: "image" },
          { path: "href", label: "Buton linki", type: "link", advancedOnly: true },
        ],
      },
    ],
  },
  {
    file: "home",
    section: "catalogPreview",
    rootIsArray: true,
    title: "Katalog Önizleme",
    description: "Ana sayfadaki katalog kartları",
    fields: [
      {
        path: "",
        label: "Kataloglar",
        type: "list",
        listLabel: "Katalog",
        itemFields: [
          { path: "title", label: "Başlık", type: "text" },
          { path: "desc", label: "Açıklama", type: "textarea", rows: 3 },
          { path: "icon", label: "Kart ikonu", type: "icon" },
          { path: "iconImage", label: "Özel ikon görseli", type: "image" },
          { path: "image", label: "Kapak görseli", type: "image" },
          { path: "href", label: "Link", type: "link", advancedOnly: true },
        ],
      },
    ],
  },
  {
    file: "home",
    section: "certificatePreview",
    rootIsArray: true,
    title: "Sertifika Önizleme",
    fields: [
      {
        path: "",
        label: "Sertifikalar",
        type: "list",
        listLabel: "Sertifika",
        itemFields: [
          { path: "title", label: "Başlık", type: "text" },
          { path: "desc", label: "Açıklama", type: "textarea", rows: 3 },
          { path: "icon", label: "Kart ikonu", type: "icon" },
          { path: "iconImage", label: "Özel ikon görseli", type: "image" },
          { path: "image", label: "Görsel", type: "image" },
          { path: "href", label: "Link", type: "link", advancedOnly: true },
        ],
      },
    ],
  },
  {
    file: "home",
    section: "engineeringPillarsSection",
    title: "Mühendislik Süreci",
    description: "Mühendislik adımları şeridinin üst başlık ve istatistikleri",
    fields: [
      { path: "eyebrow", label: "Üst etiket", type: "text" },
      { path: "title", label: "Ana başlık", type: "text" },
      { path: "subtitle", label: "Alt başlık", type: "text" },
      { path: "lead", label: "Giriş paragrafı", type: "textarea", rows: 4 },
      { path: "sidebarCardTitle", label: "Yan kart başlığı", type: "text" },
      { path: "sidebarCardDesc", label: "Yan kart açıklaması", type: "textarea", rows: 3 },
      { path: "mainCta", label: "Ana buton yazısı", type: "text" },
      { path: "cardCta", label: "Kart buton yazısı", type: "text" },
    ],
  },
  {
    file: "home",
    section: "referencePreview",
    rootIsArray: true,
    title: "Referans Önizleme",
    description: "Ana sayfadaki sektör referans kartları",
    fields: [
      {
        path: "",
        label: "Referanslar",
        type: "list",
        listLabel: "Referans",
        itemFields: [
          { path: "sector", label: "Sektör", type: "text" },
          { path: "title", label: "Başlık", type: "text" },
          { path: "example", label: "Örnek proje", type: "text" },
          { path: "projectCount", label: "Proje sayısı", type: "text" },
          { path: "image", label: "Görsel", type: "image" },
          { path: "theme", label: "Renk teması", type: "text", help: "orange, sky, emerald veya zinc", advancedOnly: true },
          { path: "href", label: "Link", type: "link", advancedOnly: true },
        ],
      },
    ],
  },
  {
    file: "home",
    section: "productCategories",
    title: "Ürün Şeridi",
    description: "Ürün kategorileri karusel başlığı ve etiketler",
    fields: [
      { path: "tag", label: "Üst etiket", type: "text" },
      { path: "title", label: "Başlık", type: "text" },
      { path: "desc", label: "Açıklama", type: "textarea", rows: 3 },
      {
        path: "items",
        label: "Kategori etiketleri",
        type: "list",
        listLabel: "Kategori",
        itemFields: [{ path: "label", label: "Etiket", type: "text" }],
      },
    ],
  },
  {
    file: "home",
    section: "pageChrome",
    title: "Buton & Etiket Metinleri",
    description: "Ana sayfadaki ortak buton, CTA ve bölüm etiketleri",
    fields: [
      { path: "catalogsVertical", label: "Kataloglar başlığı", type: "text" },
      { path: "previousSolutions", label: "Önceki çözümler", type: "text" },
      { path: "nextSolutions", label: "Sonraki çözümler", type: "text" },
      { path: "previousProducts", label: "Önceki ürünler", type: "text" },
      { path: "nextProducts", label: "Sonraki ürünler", type: "text" },
      { path: "catalogCardDesc", label: "Katalog kart açıklaması", type: "text" },
      { path: "catalogCardCta", label: "Katalog butonu", type: "text" },
      { path: "certificateCardDesc", label: "Sertifika kart açıklaması", type: "text" },
      { path: "referenceProjectWord", label: "Referans proje kelimesi", type: "text" },
      { path: "referenceExploreCta", label: "Referans keşfet butonu", type: "text" },
      { path: "pillarCta", label: "Sütun butonu", type: "text" },
      { path: "productCardCta", label: "Ürün kart butonu", type: "text" },
      { path: "companyProfileVertical", label: "Şirket profili etiketi", type: "text" },
      { path: "companyEyebrow", label: "Kurumsal kart etiketi", type: "text" },
      { path: "companyCardDesc", label: "Kurumsal kart açıklaması", type: "textarea", rows: 2 },
      { path: "pillarsFallbackTitle", label: "Mühendislik yedek başlık", type: "text", advancedOnly: true },
    ],
  },
  {
    file: "home",
    section: "companyProfileSection",
    title: "Şirket Profili",
    description: "Zaman çizelgesi ve gelecek hedefleri",
    fields: [
      { path: "timelineIntro", label: "Zaman çizelgesi girişi", type: "textarea", rows: 3 },
      { path: "timelineHeadlinePart1", label: "Başlık parça 1", type: "text" },
      { path: "timelineHeadlineEm1", label: "Başlık vurgu 1", type: "text" },
      { path: "timelineHeadlinePart2", label: "Başlık parça 2", type: "text" },
      { path: "timelineHeadlineEm2", label: "Başlık vurgu 2", type: "text" },
      { path: "timelineHeadlinePart3", label: "Başlık parça 3", type: "text" },
      {
        path: "milestones",
        label: "Kilometre taşları",
        type: "list",
        listLabel: "Yıl",
        itemFields: [
          { path: "year", label: "Yıl", type: "text" },
          { path: "title", label: "Başlık", type: "text" },
          { path: "body", label: "Açıklama", type: "textarea", rows: 3 },
          { path: "icon", label: "İkon", type: "icon" },
          { path: "iconImage", label: "Özel ikon görseli", type: "image" },
          { path: "image", label: "Görsel", type: "image" },
        ],
      },
      { path: "goalsTitle", label: "Hedefler başlığı", type: "text" },
      { path: "goalsIntro", label: "Hedefler girişi", type: "textarea", rows: 4 },
      { path: "goalsAsideImage", label: "Hedefler yan görseli", type: "image" },
      {
        path: "goalsPillars",
        label: "Hedef sütunları",
        type: "list",
        listLabel: "Hedef",
        itemFields: [
          { path: "title", label: "Başlık", type: "text" },
          { path: "body", label: "Metin", type: "textarea", rows: 4 },
          { path: "icon", label: "İkon", type: "icon" },
          { path: "iconImage", label: "Özel ikon görseli", type: "image" },
        ],
      },
      { path: "bannerTitle", label: "Banner başlığı", type: "text", advancedOnly: true },
      { path: "bannerLine1", label: "Banner satır 1", type: "text", advancedOnly: true },
      { path: "bannerLine2", label: "Banner satır 2", type: "text", advancedOnly: true },
    ],
  },
  {
    file: "home",
    section: "companyProfileCards",
    rootIsArray: true,
    title: "Şirket Profili Kartları",
    fields: [
      {
        path: "",
        label: "Kartlar",
        type: "list",
        listLabel: "Kart",
        itemFields: [
          { path: "title", label: "Başlık", type: "text" },
          { path: "image", label: "Görsel", type: "image" },
          { path: "icon", label: "Kart ikonu", type: "icon" },
          { path: "iconImage", label: "Özel ikon görseli", type: "image" },
          { path: "href", label: "Link", type: "link", advancedOnly: true },
        ],
      },
    ],
  },
  {
    file: "home",
    section: "faq",
    title: "Sık Sorulan Sorular",
    description: "Ana sayfadaki SSS bölümü",
    fields: [
      { path: "tag", label: "Üst etiket", type: "text" },
      { path: "headline", label: "Ana başlık", type: "text" },
      { path: "desc", label: "Açıklama", type: "textarea", rows: 3 },
      { path: "image", label: "Sol görsel", type: "image" },
      { path: "footerLinkLabel", label: "Alt link yazısı", type: "text" },
      { path: "footerLinkHref", label: "Alt link adresi", type: "link", advancedOnly: true },
      { path: "footerLinkAriaLabel", label: "Alt link erişilebilirlik", type: "text", advancedOnly: true },
      {
        path: "items",
        label: "Sorular",
        type: "list",
        listLabel: "Soru",
        itemFields: [
          { path: "q", label: "Soru", type: "text" },
          { path: "a", label: "Cevap", type: "textarea", rows: 4 },
          { path: "linkLabel", label: "Buton yazısı", type: "text" },
          { path: "linkHref", label: "Buton linki", type: "link", advancedOnly: true },
          { path: "linkAriaLabel", label: "Buton erişilebilirlik", type: "text", advancedOnly: true },
        ],
      },
    ],
  },
  {
    file: "home",
    section: "finalCta",
    title: "Son Çağrı Bölümü",
    description: "Sayfanın altındaki iletişim çağrısı",
    fields: [
      { path: "tag", label: "Üst etiket", type: "text" },
      { path: "title", label: "Başlık", type: "text" },
      { path: "desc", label: "Açıklama", type: "textarea", rows: 4 },
      { path: "requestQuote", label: "Teklif butonu", type: "text" },
      { path: "callBack", label: "Geri arama butonu", type: "text" },
      { path: "stat1Label", label: "İstatistik 1 etiketi", type: "text" },
      { path: "stat1Value", label: "İstatistik 1 değeri", type: "text" },
      { path: "stat2Label", label: "İstatistik 2 etiketi", type: "text" },
      { path: "stat2Value", label: "İstatistik 2 değeri", type: "text" },
      { path: "image", label: "Sağ görsel", type: "image" },
    ],
  },
];
