import type { SectionSchema } from "./types";

export const HOME_SCHEMAS: SectionSchema[] = [
  {
    file: "home",
    section: "hero",
    title: "Ana Sayfa — Büyük Başlık",
    description: "Ziyaretçilerin ilk gördüğü büyük yazılar ve istatistikler",
    fields: [
      { path: "badge", label: "Üst rozet yazısı", type: "text", help: "Başlığın üstündeki küçük etiket" },
      { path: "eyebrow", label: "Üst satır", type: "textarea", rows: 2 },
      { path: "heroLabel", label: "Ürün etiketi", type: "text" },
      { path: "titleLine1", label: "Başlık satır 1", type: "text" },
      { path: "titleLine2", label: "Başlık satır 2", type: "text" },
      { path: "titleLine3", label: "Başlık satır 3", type: "text" },
      { path: "subtitle", label: "Alt açıklama", type: "textarea", rows: 3 },
      { path: "ctaPrimary", label: "Ana buton yazısı", type: "text" },
      { path: "ctaSecondary", label: "İkinci buton yazısı", type: "text" },
      { path: "heroImageAlt", label: "Görsel açıklaması", type: "text", advancedOnly: true },
      {
        path: "stats",
        label: "İstatistikler",
        type: "list",
        listLabel: "İstatistik",
        itemFields: [
          { path: "value", label: "Sayı", type: "text" },
          { path: "label", label: "Açıklama", type: "text" },
        ],
      },
      { path: "endCard.series", label: "Kart — seri adı", type: "text" },
      { path: "endCard.title", label: "Kart — başlık", type: "text" },
      { path: "endCard.desc", label: "Kart — açıklama", type: "textarea", rows: 3 },
      { path: "endCard.cta", label: "Kart — buton yazısı", type: "text" },
      { path: "endCard.spec1Label", label: "Özellik 1 etiketi", type: "text" },
      { path: "endCard.spec1Value", label: "Özellik 1 değeri", type: "text" },
      { path: "endCard.spec2Label", label: "Özellik 2 etiketi", type: "text" },
      { path: "endCard.spec2Value", label: "Özellik 2 değeri", type: "text" },
      { path: "endCard.spec3Label", label: "Özellik 3 etiketi", type: "text" },
      { path: "endCard.spec3Value", label: "Özellik 3 değeri", type: "text" },
    ],
  },
  {
    file: "home",
    section: "faq",
    title: "Sık Sorulan Sorular",
    description: "Ana sayfadaki SSS bölümü",
    fields: [
      { path: "tag", label: "Üst etiket", type: "text" },
      { path: "headline", label: "Ana başlık", type: "text" },
      { path: "desc", label: "Açıklama", type: "textarea", rows: 3 },
      { path: "footerLinkLabel", label: "Alt link yazısı", type: "text" },
      { path: "footerLinkHref", label: "Alt link adresi", type: "link", advancedOnly: true },
      { path: "footerLinkAriaLabel", label: "Alt link erişilebilirlik", type: "text", advancedOnly: true },
      {
        path: "items",
        label: "Sorular",
        type: "list",
        listLabel: "Soru",
        itemFields: [
          { path: "q", label: "Soru", type: "text" },
          { path: "a", label: "Cevap", type: "textarea", rows: 4 },
          { path: "linkLabel", label: "Buton yazısı", type: "text" },
          { path: "linkHref", label: "Buton linki", type: "link", advancedOnly: true },
          { path: "linkAriaLabel", label: "Buton erişilebilirlik", type: "text", advancedOnly: true },
        ],
      },
    ],
  },
  {
    file: "home",
    section: "finalCta",
    title: "Son Çağrı Bölümü",
    description: "Sayfanın altındaki iletişim çağrısı",
    fields: [
      { path: "tag", label: "Üst etiket", type: "text" },
      { path: "title", label: "Başlık", type: "text" },
      { path: "desc", label: "Açıklama", type: "textarea", rows: 4 },
      { path: "requestQuote", label: "Teklif butonu", type: "text" },
      { path: "callBack", label: "Geri arama butonu", type: "text" },
      { path: "stat1Label", label: "İstatistik 1 etiketi", type: "text" },
      { path: "stat1Value", label: "İstatistik 1 değeri", type: "text" },
      { path: "stat2Label", label: "İstatistik 2 etiketi", type: "text" },
      { path: "stat2Value", label: "İstatistik 2 değeri", type: "text" },
      { path: "image", label: "Görsel yolu", type: "image" },
    ],
  },
  {
    file: "home",
    section: "pillars",
    rootIsArray: true,
    title: "3 Sütun Bölümü",
    description: "Ana sayfadaki 3 sütunlu tanıtım kartları",
    fields: [
      {
        path: "",
        label: "Sütunlar",
        type: "list",
        listLabel: "Sütun",
        itemFields: [
          { path: "tag", label: "Etiket", type: "text" },
          { path: "title", label: "Başlık", type: "text" },
          { path: "intro", label: "Giriş metni", type: "textarea", rows: 4 },
          { path: "cta", label: "Buton yazısı", type: "text" },
          { path: "href", label: "Buton linki", type: "link", advancedOnly: true },
        ],
      },
    ],
  },
];
