import type { SectionSchema } from "./types";

export const HOME_SCHEMAS: SectionSchema[] = [
  {
    file: "home",
    section: "hero",
    title: "Ana Sayfa ù Bùyùk Ba?l?k",
    description: "Ziyaretùilerin ilk gùrdù?ù bùyùk yaz?lar ve istatistikler",
    fields: [
      { path: "badge", label: "ùst rozet yaz?s?", type: "text", help: "Ba?l???n ùstùndeki kùùùk etiket" },
      { path: "eyebrow", label: "ùst sat?r", type: "textarea", rows: 2 },
      { path: "heroLabel", label: "ùrùn etiketi", type: "text" },
      { path: "titleLine1", label: "Ba?l?k sat?r 1", type: "text" },
      { path: "titleLine2", label: "Ba?l?k sat?r 2", type: "text" },
      { path: "titleLine3", label: "Ba?l?k sat?r 3", type: "text" },
      { path: "subtitle", label: "Alt aù?klama", type: "textarea", rows: 3 },
      { path: "ctaPrimary", label: "Ana buton yaz?s?", type: "text" },
      { path: "ctaSecondary", label: "?kinci buton yaz?s?", type: "text" },
      { path: "heroImageAlt", label: "Gùrsel aù?klamas?", type: "text", advancedOnly: true },
      {
        path: "stats",
        label: "?statistikler",
        type: "list",
        listLabel: "?statistik",
        itemFields: [
          { path: "value", label: "Say?", type: "text" },
          { path: "label", label: "Aù?klama", type: "text" },
        ],
      },
      { path: "endCard.series", label: "Kart ù seri ad?", type: "text" },
      { path: "endCard.title", label: "Kart ù ba?l?k", type: "text" },
      { path: "endCard.desc", label: "Kart ù aù?klama", type: "textarea", rows: 3 },
      { path: "endCard.cta", label: "Kart ù buton yaz?s?", type: "text" },
      { path: "endCard.spec1Label", label: "ùzellik 1 etiketi", type: "text" },
      { path: "endCard.spec1Value", label: "ùzellik 1 de?eri", type: "text" },
      { path: "endCard.spec2Label", label: "ùzellik 2 etiketi", type: "text" },
      { path: "endCard.spec2Value", label: "ùzellik 2 de?eri", type: "text" },
      { path: "endCard.spec3Label", label: "ùzellik 3 etiketi", type: "text" },
      { path: "endCard.spec3Value", label: "ùzellik 3 de?eri", type: "text" },
    ],
  },
  {
    file: "home",
    section: "faq",
    title: "S?k Sorulan Sorular",
    description: "Ana sayfadaki SSS bùlùmù",
    fields: [
      { path: "tag", label: "ùst etiket", type: "text" },
      { path: "headline", label: "Ana ba?l?k", type: "text" },
      { path: "desc", label: "Aù?klama", type: "textarea", rows: 3 },
      { path: "footerLinkLabel", label: "Alt link yaz?s?", type: "text" },
      { path: "footerLinkHref", label: "Alt link adresi", type: "link", advancedOnly: true },
      { path: "footerLinkAriaLabel", label: "Alt link eri?ilebilirlik", type: "text", advancedOnly: true },
      {
        path: "items",
        label: "Sorular",
        type: "list",
        listLabel: "Soru",
        itemFields: [
          { path: "q", label: "Soru", type: "text" },
          { path: "a", label: "Cevap", type: "textarea", rows: 4 },
          { path: "linkLabel", label: "Buton yaz?s?", type: "text" },
          { path: "linkHref", label: "Buton linki", type: "link", advancedOnly: true },
          { path: "linkAriaLabel", label: "Buton eri?ilebilirlik", type: "text", advancedOnly: true },
        ],
      },
    ],
  },
  {
    file: "home",
    section: "finalCta",
    title: "Son ùa?r? Bùlùmù",
    description: "Sayfan?n alt?ndaki ileti?im ùa?r?s?",
    fields: [
      { path: "tag", label: "ùst etiket", type: "text" },
      { path: "title", label: "Ba?l?k", type: "text" },
      { path: "desc", label: "Aù?klama", type: "textarea", rows: 4 },
      { path: "requestQuote", label: "Teklif butonu", type: "text" },
      { path: "callBack", label: "Geri arama butonu", type: "text" },
      { path: "stat1Label", label: "?statistik 1 etiketi", type: "text" },
      { path: "stat1Value", label: "?statistik 1 de?eri", type: "text" },
      { path: "stat2Label", label: "?statistik 2 etiketi", type: "text" },
      { path: "stat2Value", label: "?statistik 2 de?eri", type: "text" },
      { path: "image", label: "Gùrsel yolu", type: "image" },
    ],
  },
  {
    file: "home",
    section: "pillars",
    rootIsArray: true,
    title: "3 Sùtun Bùlùmù",
    description: "Ana sayfadaki ùù sùtunlu tan?t?m kartlar?",
    fields: [
      {
        path: "",
        label: "Sùtunlar",
        type: "list",
        listLabel: "Sùtun",
        itemFields: [
          { path: "tag", label: "Etiket", type: "text" },
          { path: "title", label: "Ba?l?k", type: "text" },
          { path: "intro", label: "Giri? metni", type: "textarea", rows: 4 },
          { path: "cta", label: "Buton yaz?s?", type: "text" },
          { path: "href", label: "Buton linki", type: "link", advancedOnly: true },
        ],
      },
    ],
  },
];
