import type { Locale } from "@/i18n/config";

export type ProductCatalogUi = {
  catalogTitle: string;
  categoriesTitle: string;
  searchPlaceholder: string;
  filterSeries: string;
  filterDescription: string;
  filterAllSeries: string;
  filterAllSeriesModels: string;
  filterModelRange: string;
  filterProductType: string;
  filterAny: string;
  filterMin: string;
  filterMax: string;
  searchPlaceholderShort: string;
  filterApply: string;
  filterReset: string;
  comingSoon: string;
  technicalDetails: string;
  perfectusBadge: string;
  perfectusCta: string;
  techLibrary: string;
  viewAll: string;
  catalogsTitle: string;
  guidesTitle: string;
  sidebarSupportTitle: string;
  sidebarSupportDesc: string;
  sidebarSupportCta: string;
  topBarContact: string;
  topBarSettings: string;
  openMenu: string;
  closeMenu: string;
  noResults: string;
  specFlow: string;
  specPressure: string;
  productNo: string;
  home: string;
  products: string;
  docCatalogTitle: string;
  docGeneralCatalog: string;
  docInstallManual: string;
  docDatasheets: string;
  modelsLabel: string;
  accessoryType: string;
  pageProductsSuffix: string;
  allSolutions: string;
  specsTitle: string;
  galleryTitle: string;
  specSingular: string;
  specPlural: string;
  tableTitle: string;
};

const UI: Record<Locale, ProductCatalogUi> = {
  tr: {
    catalogTitle: "Ürün Kataloğu",
    categoriesTitle: "Ürün Kategorileri",
    searchPlaceholder: "Ürün veya model ara…",
    filterSeries: "Ürün Ailesi — Seri",
    filterDescription: "Ürün Açıklaması",
    filterAllSeries: "Tüm seriler",
    filterAllSeriesModels: "Tüm ürün aileleri",
    filterModelRange: "Ürün Serisi",
    filterProductType: "Ürün Serisi",
    filterAny: "Herhangi",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Arama yapın…",
    filterApply: "Filtrele",
    filterReset: "Sıfırla",
    comingSoon: "Yakında",
    technicalDetails: "Teknik detayları incele",
    perfectusBadge: "Online tool",
    perfectusCta: "PerfectusAir seçim aracı",
    techLibrary: "Teknik kütüphane",
    viewAll: "Tümünü görüntüle",
    catalogsTitle: "Ürün katalogları",
    guidesTitle: "Kılavuzlar & sertifikalar",
    sidebarSupportTitle: "Teknik destek",
    sidebarSupportDesc: "Seçim, montaj ve proje danışmanlığı için mühendislik ekibimizle iletişime geçin.",
    sidebarSupportCta: "Destek talebi",
    topBarContact: "İletişim",
    topBarSettings: "Teknik merkez",
    openMenu: "Kategorileri aç",
    closeMenu: "Kapat",
    noResults: "Filtrelere uygun ürün bulunamadı.",
    specFlow: "Max debi",
    specPressure: "Basınç",
    productNo: "Ürün No.",
    home: "Ana sayfa",
    products: "Ürünler",
    docCatalogTitle: "{name} ürün kataloğu",
    docGeneralCatalog: "NOVVES genel ürün kataloğu",
    docInstallManual: "Montaj ve bakım kılavuzu",
    docDatasheets: "Teknik veri föyleri",
    modelsLabel: "model",
    accessoryType: "Aksesuar",
    pageProductsSuffix: "ürünleri",
    allSolutions: "Çözümlerin Tümünü Gör",
    specsTitle: "Teknik Özellikler",
    galleryTitle: "Ürün Görünümü",
    specSingular: "Özellik",
    specPlural: "Özellikler",
    tableTitle: "Model Serisi ve Teknik Veriler",
  },
  en: {
    catalogTitle: "Product Catalog",
    categoriesTitle: "Product Categories",
    searchPlaceholder: "Search products or models…",
    filterSeries: "Product family — series",
    filterDescription: "Description",
    filterAllSeries: "All series",
    filterAllSeriesModels: "All product families",
    filterModelRange: "Product series",
    filterProductType: "Product series",
    filterAny: "Any",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Search…",
    filterApply: "Filter",
    filterReset: "Reset",
    comingSoon: "Coming soon",
    technicalDetails: "View technical details",
    perfectusBadge: "Online tool",
    perfectusCta: "PerfectusAir selection tool",
    techLibrary: "Technical library",
    viewAll: "View all",
    catalogsTitle: "Product catalogs",
    guidesTitle: "Manuals & certificates",
    sidebarSupportTitle: "Technical support",
    sidebarSupportDesc: "Contact our engineering team for selection, installation and project consulting.",
    sidebarSupportCta: "Request support",
    topBarContact: "Contact",
    topBarSettings: "Technical center",
    openMenu: "Open categories",
    closeMenu: "Close",
    noResults: "No products match your filters.",
    specFlow: "Max flow",
    specPressure: "Pressure",
    productNo: "Product No.",
    home: "Home",
    products: "Products",
    docCatalogTitle: "{name} product catalog",
    docGeneralCatalog: "NOVVES general product catalog",
    docInstallManual: "Installation & maintenance manual",
    docDatasheets: "Technical datasheets",
    modelsLabel: "models",
    accessoryType: "Accessory",
    pageProductsSuffix: "products",
    allSolutions: "View All Solutions",
    specsTitle: "Technical Specifications",
    galleryTitle: "Product Views",
    specSingular: "Specification",
    specPlural: "Specifications",
    tableTitle: "Model Series and Technical Data",
  },
  ru: {
    catalogTitle: "Каталог продукции",
    categoriesTitle: "Категории продукции",
    searchPlaceholder: "Поиск по продуктам или моделям…",
    filterSeries: "Семейство продукции",
    filterDescription: "Описание",
    filterAllSeries: "Все серии",
    filterAllSeriesModels: "Все модели серий",
    filterModelRange: "Серия продукции",
    filterProductType: "Серия продукции",
    filterAny: "Любой",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Поиск…",
    filterApply: "Фильтр",
    filterReset: "Сброс",
    comingSoon: "Скоро",
    technicalDetails: "Технические характеристики",
    perfectusBadge: "Онлайн-инструмент",
    perfectusCta: "Инструмент подбора PerfectusAir",
    techLibrary: "Техническая библиотека",
    viewAll: "Показать все",
    catalogsTitle: "Каталоги продукции",
    guidesTitle: "Руководства и сертификаты",
    sidebarSupportTitle: "Техническая поддержка",
    sidebarSupportDesc: "Свяжитесь с нашей инженерной командой по вопросам подбора, монтажа и проектного консультирования.",
    sidebarSupportCta: "Запросить поддержку",
    topBarContact: "Контакты",
    topBarSettings: "Технический центр",
    openMenu: "Открыть категории",
    closeMenu: "Закрыть",
    noResults: "Нет продуктов, соответствующих фильтрам.",
    specFlow: "Макс. расход",
    specPressure: "Давление",
    productNo: "Артикул",
    home: "Главная",
    products: "Продукция",
    docCatalogTitle: "Каталог продукции {name}",
    docGeneralCatalog: "Общий каталог продукции NOVVES",
    docInstallManual: "Руководство по монтажу и обслуживанию",
    docDatasheets: "Технические спецификации",
    modelsLabel: "моделей",
    accessoryType: "Аксессуар",
    pageProductsSuffix: "продукция",
    allSolutions: "Посмотреть все решения",
    specsTitle: "Технические характеристики",
    galleryTitle: "Виды продукта",
    specSingular: "характеристика",
    specPlural: "характеристик",
    tableTitle: "Модельный ряд и технические данные",
  },
  ar: {
    catalogTitle: "كتالوج المنتجات",
    categoriesTitle: "فئات المنتجات",
    searchPlaceholder: "ابحث عن منتجات أو موديلات…",
    filterSeries: "عائلة المنتجات",
    filterDescription: "الوصف",
    filterAllSeries: "كل السلاسل",
    filterAllSeriesModels: "كل موديلات السلاسل",
    filterModelRange: "سلسلة المنتجات",
    filterProductType: "سلسلة المنتجات",
    filterAny: "أي",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "ابحث…",
    filterApply: "تصفية",
    filterReset: "إعادة ضبط",
    comingSoon: "قريباً",
    technicalDetails: "عرض التفاصيل الفنية",
    perfectusBadge: "أداة عبر الإنترنت",
    perfectusCta: "أداة اختيار PerfectusAir",
    techLibrary: "المكتبة الفنية",
    viewAll: "عرض الكل",
    catalogsTitle: "كتالوجات المنتجات",
    guidesTitle: "الأدلة والشهادات",
    sidebarSupportTitle: "الدعم الفني",
    sidebarSupportDesc: "تواصل مع فريقنا الهندسي للاختيار والتركيب واستشارات المشاريع.",
    sidebarSupportCta: "طلب الدعم",
    topBarContact: "اتصل بنا",
    topBarSettings: "المركز الفني",
    openMenu: "فتح الفئات",
    closeMenu: "إغلاق",
    noResults: "لا توجد منتجات تطابق عوامل التصفية.",
    specFlow: "أقصى تدفق",
    specPressure: "الضغط",
    productNo: "رقم المنتج",
    home: "الرئيسية",
    products: "المنتجات",
    docCatalogTitle: "كتالوج منتجات {name}",
    docGeneralCatalog: "كتالوج منتجات NOVVES العام",
    docInstallManual: "دليل التركيب والصيانة",
    docDatasheets: "صحائف البيانات الفنية",
    modelsLabel: "موديل",
    accessoryType: "ملحق",
    pageProductsSuffix: "منتجات",
    allSolutions: "عرض جميع الحلول",
    specsTitle: "المواصفات الفنية",
    galleryTitle: "صور المنتج",
    specSingular: "مواصفة",
    specPlural: "مواصفات",
    tableTitle: "سلسلة الموديلات والبيانات الفنية",
  },
  de: {
    catalogTitle: "Produktkatalog",
    categoriesTitle: "Produktkategorien",
    searchPlaceholder: "Produkte oder Modelle suchen…",
    filterSeries: "Produktfamilie",
    filterDescription: "Beschreibung",
    filterAllSeries: "Alle Serien",
    filterAllSeriesModels: "Alle Seriemodelle",
    filterModelRange: "Produktserie",
    filterProductType: "Produktserie",
    filterAny: "Beliebig",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Suchen…",
    filterApply: "Filtern",
    filterReset: "Zurücksetzen",
    comingSoon: "Demnächst",
    technicalDetails: "Technische Details ansehen",
    perfectusBadge: "Online-Tool",
    perfectusCta: "PerfectusAir Auswahltool",
    techLibrary: "Technische Bibliothek",
    viewAll: "Alle anzeigen",
    catalogsTitle: "Produktkataloge",
    guidesTitle: "Handbücher & Zertifikate",
    sidebarSupportTitle: "Technischer Support",
    sidebarSupportDesc: "Kontaktieren Sie unser Engineering-Team für Auswahl, Montage und Projektberatung.",
    sidebarSupportCta: "Support anfragen",
    topBarContact: "Kontakt",
    topBarSettings: "Technikzentrum",
    openMenu: "Kategorien öffnen",
    closeMenu: "Schließen",
    noResults: "Keine Produkte entsprechen Ihren Filtern.",
    specFlow: "Max. Volumenstrom",
    specPressure: "Druck",
    productNo: "Produkt-Nr.",
    home: "Startseite",
    products: "Produkte",
    docCatalogTitle: "{name} Produktkatalog",
    docGeneralCatalog: "NOVVES Gesamtproduktkatalog",
    docInstallManual: "Montage- und Wartungshandbuch",
    docDatasheets: "Technische Datenblätter",
    modelsLabel: "Modelle",
    accessoryType: "Zubehör",
    pageProductsSuffix: "Produkte",
    allSolutions: "Alle Lösungen ansehen",
    specsTitle: "Technische Daten",
    galleryTitle: "Produktansichten",
    specSingular: "Spezifikation",
    specPlural: "Spezifikationen",
    tableTitle: "Modellreihe und technische Daten",
  },
  it: {
    catalogTitle: "Catalogo prodotti",
    categoriesTitle: "Categorie prodotti",
    searchPlaceholder: "Cerca prodotti o modelli…",
    filterSeries: "Famiglia di prodotti",
    filterDescription: "Descrizione",
    filterAllSeries: "Tutte le serie",
    filterAllSeriesModels: "Tutti i modelli delle serie",
    filterModelRange: "Serie prodotto",
    filterProductType: "Serie prodotto",
    filterAny: "Qualsiasi",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Cerca…",
    filterApply: "Filtra",
    filterReset: "Reimposta",
    comingSoon: "In arrivo",
    technicalDetails: "Vedi dettagli tecnici",
    perfectusBadge: "Strumento online",
    perfectusCta: "Strumento di selezione PerfectusAir",
    techLibrary: "Libreria tecnica",
    viewAll: "Vedi tutto",
    catalogsTitle: "Cataloghi prodotti",
    guidesTitle: "Manuali e certificati",
    sidebarSupportTitle: "Supporto tecnico",
    sidebarSupportDesc: "Contatta il nostro team tecnico per selezione, installazione e consulenza di progetto.",
    sidebarSupportCta: "Richiedi supporto",
    topBarContact: "Contatti",
    topBarSettings: "Centro tecnico",
    openMenu: "Apri categorie",
    closeMenu: "Chiudi",
    noResults: "Nessun prodotto corrisponde ai filtri.",
    specFlow: "Portata max",
    specPressure: "Pressione",
    productNo: "N. prodotto",
    home: "Home",
    products: "Prodotti",
    docCatalogTitle: "Catalogo prodotti {name}",
    docGeneralCatalog: "Catalogo generale prodotti NOVVES",
    docInstallManual: "Manuale di installazione e manutenzione",
    docDatasheets: "Schede tecniche",
    modelsLabel: "modelli",
    accessoryType: "Accessorio",
    pageProductsSuffix: "prodotti",
    allSolutions: "Vedi tutte le soluzioni",
    specsTitle: "Specifiche tecniche",
    galleryTitle: "Viste del prodotto",
    specSingular: "specifica",
    specPlural: "specifiche",
    tableTitle: "Serie di modelli e dati tecnici",
  },
  fr: {
    catalogTitle: "Catalogue de produits",
    categoriesTitle: "Catégories de produits",
    searchPlaceholder: "Rechercher un produit ou un modèle…",
    filterSeries: "Famille de produits",
    filterDescription: "Description",
    filterAllSeries: "Toutes les gammes",
    filterAllSeriesModels: "Tous les modèles",
    filterModelRange: "Gamme de produits",
    filterProductType: "Gamme de produits",
    filterAny: "Tous",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Rechercher…",
    filterApply: "Filtrer",
    filterReset: "Réinitialiser",
    comingSoon: "Bientôt disponible",
    technicalDetails: "Voir les détails techniques",
    perfectusBadge: "Outil en ligne",
    perfectusCta: "Outil de sélection PerfectusAir",
    techLibrary: "Bibliothèque technique",
    viewAll: "Tout afficher",
    catalogsTitle: "Catalogues de produits",
    guidesTitle: "Manuels et certificats",
    sidebarSupportTitle: "Support technique",
    sidebarSupportDesc: "Contactez notre équipe d'ingénierie pour la sélection, l'installation et le conseil projet.",
    sidebarSupportCta: "Demander de l'aide",
    topBarContact: "Contact",
    topBarSettings: "Centre technique",
    openMenu: "Ouvrir les catégories",
    closeMenu: "Fermer",
    noResults: "Aucun produit ne correspond à vos filtres.",
    specFlow: "Débit max",
    specPressure: "Pression",
    productNo: "Réf. produit",
    home: "Accueil",
    products: "Produits",
    docCatalogTitle: "Catalogue de produits {name}",
    docGeneralCatalog: "Catalogue général des produits NOVVES",
    docInstallManual: "Manuel d'installation et d'entretien",
    docDatasheets: "Fiches techniques",
    modelsLabel: "modèles",
    accessoryType: "Accessoire",
    pageProductsSuffix: "produits",
    allSolutions: "Voir toutes les solutions",
    specsTitle: "Caractéristiques techniques",
    galleryTitle: "Vues du produit",
    specSingular: "caractéristique",
    specPlural: "caractéristiques",
    tableTitle: "Gamme de modèles et données techniques",
  },
  az: {
    catalogTitle: "Məhsul Kataloqu",
    categoriesTitle: "Məhsul Kateqoriyaları",
    searchPlaceholder: "Məhsul və ya model axtar…",
    filterSeries: "Məhsul ailəsi",
    filterDescription: "Təsvir",
    filterAllSeries: "Bütün seriyalar",
    filterAllSeriesModels: "Bütün seriya modelləri",
    filterModelRange: "Məhsul seriyası",
    filterProductType: "Məhsul seriyası",
    filterAny: "İstənilən",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Axtar…",
    filterApply: "Filtrlə",
    filterReset: "Sıfırla",
    comingSoon: "Tezliklə",
    technicalDetails: "Texniki detallara bax",
    perfectusBadge: "Onlayn alət",
    perfectusCta: "PerfectusAir seçim aləti",
    techLibrary: "Texniki kitabxana",
    viewAll: "Hamısına bax",
    catalogsTitle: "Məhsul kataloqları",
    guidesTitle: "Təlimatlar və sertifikatlar",
    sidebarSupportTitle: "Texniki dəstək",
    sidebarSupportDesc: "Seçim, quraşdırma və layihə məsləhəti üçün mühəndislik komandamızla əlaqə saxlayın.",
    sidebarSupportCta: "Dəstək tələbi",
    topBarContact: "Əlaqə",
    topBarSettings: "Texniki mərkəz",
    openMenu: "Kateqoriyaları aç",
    closeMenu: "Bağla",
    noResults: "Filtrlərə uyğun məhsul tapılmadı.",
    specFlow: "Maks. debi",
    specPressure: "Təzyiq",
    productNo: "Məhsul No.",
    home: "Ana səhifə",
    products: "Məhsullar",
    docCatalogTitle: "{name} məhsul kataloqu",
    docGeneralCatalog: "NOVVES ümumi məhsul kataloqu",
    docInstallManual: "Quraşdırma və texniki xidmət təlimatı",
    docDatasheets: "Texniki məlumat vərəqələri",
    modelsLabel: "model",
    accessoryType: "Aksesuar",
    pageProductsSuffix: "məhsulları",
    allSolutions: "Bütün həlləri gör",
    specsTitle: "Texniki Xüsusiyyətlər",
    galleryTitle: "Məhsul Görünüşləri",
    specSingular: "xüsusiyyət",
    specPlural: "xüsusiyyətlər",
    tableTitle: "Model Seriyası və Texniki Məlumatlar",
  },
  kk: {
    catalogTitle: "Өнім каталогы",
    categoriesTitle: "Өнім санаттары",
    searchPlaceholder: "Өнім немесе модель іздеу…",
    filterSeries: "Өнім тобы",
    filterDescription: "Сипаттама",
    filterAllSeries: "Барлық сериялар",
    filterAllSeriesModels: "Барлық серия модельдері",
    filterModelRange: "Өнім сериясы",
    filterProductType: "Өнім сериясы",
    filterAny: "Кез келген",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Іздеу…",
    filterApply: "Сүзу",
    filterReset: "Тазарту",
    comingSoon: "Жақында",
    technicalDetails: "Техникалық мәліметтерді қарау",
    perfectusBadge: "Онлайн құрал",
    perfectusCta: "PerfectusAir таңдау құралы",
    techLibrary: "Техникалық кітапхана",
    viewAll: "Барлығын көру",
    catalogsTitle: "Өнім каталогтары",
    guidesTitle: "Нұсқаулықтар және сертификаттар",
    sidebarSupportTitle: "Техникалық қолдау",
    sidebarSupportDesc: "Таңдау, монтаж және жоба бойынша кеңес алу үшін инженерлік тобымызбен байланысыңыз.",
    sidebarSupportCta: "Қолдау сұрау",
    topBarContact: "Байланыс",
    topBarSettings: "Техникалық орталық",
    openMenu: "Санаттарды ашу",
    closeMenu: "Жабу",
    noResults: "Сүзгілерге сәйкес өнім табылмады.",
    specFlow: "Макс. шығын",
    specPressure: "Қысым",
    productNo: "Өнім №",
    home: "Басты бет",
    products: "Өнімдер",
    docCatalogTitle: "{name} өнім каталогы",
    docGeneralCatalog: "NOVVES жалпы өнім каталогы",
    docInstallManual: "Монтаж және техникалық қызмет көрсету нұсқаулығы",
    docDatasheets: "Техникалық деректер парақтары",
    modelsLabel: "модель",
    accessoryType: "Керек-жарақ",
    pageProductsSuffix: "өнімдері",
    allSolutions: "Барлық шешімдерді көру",
    specsTitle: "Техникалық сипаттамалар",
    galleryTitle: "Өнім көріністері",
    specSingular: "сипаттама",
    specPlural: "сипаттамалар",
    tableTitle: "Модель сериясы және техникалық деректер",
  },
  tg: {
    catalogTitle: "Каталоги маҳсулот",
    categoriesTitle: "Категорияҳои маҳсулот",
    searchPlaceholder: "Ҷустуҷӯи маҳсулот ё модел…",
    filterSeries: "Оилаи маҳсулот",
    filterDescription: "Тавсиф",
    filterAllSeries: "Ҳамаи силсилаҳо",
    filterAllSeriesModels: "Ҳамаи моделҳои силсила",
    filterModelRange: "Силсилаи маҳсулот",
    filterProductType: "Силсилаи маҳсулот",
    filterAny: "Ҳар кадом",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Ҷустуҷӯ…",
    filterApply: "Филтр",
    filterReset: "Аз нав",
    comingSoon: "Ба зудӣ",
    technicalDetails: "Тафсилоти техникӣ",
    perfectusBadge: "Абзори онлайн",
    perfectusCta: "Абзори интихоби PerfectusAir",
    techLibrary: "Китобхонаи техникӣ",
    viewAll: "Ҳамаро дидан",
    catalogsTitle: "Каталогҳои маҳсулот",
    guidesTitle: "Дастурҳо ва сертификатҳо",
    sidebarSupportTitle: "Дастгирии техникӣ",
    sidebarSupportDesc: "Барои интихоб, насб ва машварати лоиҳа бо дастаи муҳандисии мо тамос гиред.",
    sidebarSupportCta: "Дархости дастгирӣ",
    topBarContact: "Тамос",
    topBarSettings: "Маркази техникӣ",
    openMenu: "Кушодани категорияҳо",
    closeMenu: "Пӯшидан",
    noResults: "Ҳеҷ маҳсулоте ба филтрҳои шумо мувофиқ нест.",
    specFlow: "Ҳаҷми максималӣ",
    specPressure: "Фишор",
    productNo: "Рақами маҳсулот",
    home: "Асосӣ",
    products: "Маҳсулот",
    docCatalogTitle: "Каталоги маҳсулоти {name}",
    docGeneralCatalog: "Каталоги умумии маҳсулоти NOVVES",
    docInstallManual: "Дастури насб ва нигоҳдорӣ",
    docDatasheets: "Варақаҳои маълумоти техникӣ",
    modelsLabel: "модел",
    accessoryType: "Лавозимот",
    pageProductsSuffix: "маҳсулот",
    allSolutions: "Ҳамаи ҳалҳоро дидан",
    specsTitle: "Хусусиятҳои техникӣ",
    galleryTitle: "Намоиши маҳсулот",
    specSingular: "хусусият",
    specPlural: "хусусиятҳо",
    tableTitle: "Силсилаи моделҳо ва маълумоти техникӣ",
  },
  es: {
    catalogTitle: "Catálogo de productos",
    categoriesTitle: "Categorías de productos",
    searchPlaceholder: "Buscar productos o modelos…",
    filterSeries: "Familia de productos",
    filterDescription: "Descripción",
    filterAllSeries: "Todas las series",
    filterAllSeriesModels: "Todos los modelos de la serie",
    filterModelRange: "Serie de productos",
    filterProductType: "Serie de productos",
    filterAny: "Cualquiera",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Buscar…",
    filterApply: "Filtrar",
    filterReset: "Restablecer",
    comingSoon: "Próximamente",
    technicalDetails: "Ver detalles técnicos",
    perfectusBadge: "Herramienta en línea",
    perfectusCta: "Herramienta de selección PerfectusAir",
    techLibrary: "Biblioteca técnica",
    viewAll: "Ver todo",
    catalogsTitle: "Catálogos de productos",
    guidesTitle: "Manuales y certificados",
    sidebarSupportTitle: "Soporte técnico",
    sidebarSupportDesc: "Contacte con nuestro equipo de ingeniería para selección, instalación y asesoramiento de proyectos.",
    sidebarSupportCta: "Solicitar soporte",
    topBarContact: "Contacto",
    topBarSettings: "Centro técnico",
    openMenu: "Abrir categorías",
    closeMenu: "Cerrar",
    noResults: "Ningún producto coincide con sus filtros.",
    specFlow: "Caudal máx.",
    specPressure: "Presión",
    productNo: "N.º de producto",
    home: "Inicio",
    products: "Productos",
    docCatalogTitle: "Catálogo de productos {name}",
    docGeneralCatalog: "Catálogo general de productos NOVVES",
    docInstallManual: "Manual de instalación y mantenimiento",
    docDatasheets: "Fichas técnicas",
    modelsLabel: "modelos",
    accessoryType: "Accesorio",
    pageProductsSuffix: "productos",
    allSolutions: "Ver todas las soluciones",
    specsTitle: "Especificaciones técnicas",
    galleryTitle: "Vistas del producto",
    specSingular: "especificación",
    specPlural: "especificaciones",
    tableTitle: "Serie de modelos y datos técnicos",
  },
  zh: {
    catalogTitle: "产品目录",
    categoriesTitle: "产品分类",
    searchPlaceholder: "搜索产品或型号…",
    filterSeries: "产品家族",
    filterDescription: "产品说明",
    filterAllSeries: "全部系列",
    filterAllSeriesModels: "全部系列型号",
    filterModelRange: "产品系列",
    filterProductType: "产品系列",
    filterAny: "不限",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "搜索…",
    filterApply: "筛选",
    filterReset: "重置",
    comingSoon: "即将推出",
    technicalDetails: "查看技术详情",
    perfectusBadge: "在线工具",
    perfectusCta: "PerfectusAir 选型工具",
    techLibrary: "技术资料库",
    viewAll: "查看全部",
    catalogsTitle: "产品目录",
    guidesTitle: "手册与证书",
    sidebarSupportTitle: "技术支持",
    sidebarSupportDesc: "如需选型、安装及项目咨询，请联系我们的工程团队。",
    sidebarSupportCta: "申请支持",
    topBarContact: "联系我们",
    topBarSettings: "技术中心",
    openMenu: "打开分类",
    closeMenu: "关闭",
    noResults: "没有符合筛选条件的产品。",
    specFlow: "最大风量",
    specPressure: "压力",
    productNo: "产品编号",
    home: "首页",
    products: "产品",
    docCatalogTitle: "{name} 产品目录",
    docGeneralCatalog: "NOVVES 通用产品目录",
    docInstallManual: "安装与维护手册",
    docDatasheets: "技术数据表",
    modelsLabel: "款",
    accessoryType: "配件",
    pageProductsSuffix: "产品",
    allSolutions: "查看所有解决方案",
    specsTitle: "技术规格",
    galleryTitle: "产品视图",
    specSingular: "项规格",
    specPlural: "项规格",
    tableTitle: "型号系列和技术数据",
  },
  ur: {
    catalogTitle: "پروڈکٹ کیٹلاگ",
    categoriesTitle: "پروڈکٹ کیٹیگریز",
    searchPlaceholder: "پروڈکٹ یا ماڈل تلاش کریں…",
    filterSeries: "پروڈکٹ فیملی",
    filterDescription: "تفصیل",
    filterAllSeries: "تمام سیریز",
    filterAllSeriesModels: "تمام سیریز ماڈلز",
    filterModelRange: "پروڈکٹ سیریز",
    filterProductType: "پروڈکٹ سیریز",
    filterAny: "کوئی بھی",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "تلاش کریں…",
    filterApply: "فلٹر",
    filterReset: "ری سیٹ",
    comingSoon: "جلد آ رہا ہے",
    technicalDetails: "تکنیکی تفصیلات دیکھیں",
    perfectusBadge: "آن لائن ٹول",
    perfectusCta: "PerfectusAir سلیکشن ٹول",
    techLibrary: "تکنیکی لائبریری",
    viewAll: "سب دیکھیں",
    catalogsTitle: "پروڈکٹ کیٹلاگز",
    guidesTitle: "مینوئلز اور سرٹیفکیٹس",
    sidebarSupportTitle: "تکنیکی معاونت",
    sidebarSupportDesc: "سلیکشن، تنصیب اور پروجیکٹ مشاورت کے لیے ہماری انجینئرنگ ٹیم سے رابطہ کریں۔",
    sidebarSupportCta: "معاونت کی درخواست",
    topBarContact: "رابطہ",
    topBarSettings: "تکنیکی مرکز",
    openMenu: "کیٹیگریز کھولیں",
    closeMenu: "بند کریں",
    noResults: "آپ کے فلٹرز سے کوئی پروڈکٹ مطابقت نہیں رکھتا۔",
    specFlow: "زیادہ سے زیادہ فلو",
    specPressure: "پریشر",
    productNo: "پروڈکٹ نمبر",
    home: "ہوم",
    products: "پروڈکٹس",
    docCatalogTitle: "{name} پروڈکٹ کیٹلاگ",
    docGeneralCatalog: "NOVVES جنرل پروڈکٹ کیٹلاگ",
    docInstallManual: "تنصیب اور دیکھ بھال مینوئل",
    docDatasheets: "تکنیکی ڈیٹا شیٹس",
    modelsLabel: "ماڈلز",
    accessoryType: "لوازم",
    pageProductsSuffix: "مصنوعات",
    allSolutions: "تمام حل دیکھیں",
    specsTitle: "تکنیکی تفصیلات",
    galleryTitle: "پروڈکٹ مناظر",
    specSingular: "تفصیل",
    specPlural: "تفصیلات",
    tableTitle: "ماڈل سیریز اور تکنیکی ڈیٹا",
  },
  lt: {
    catalogTitle: "Produktų katalogas",
    categoriesTitle: "Produktų kategorijos",
    searchPlaceholder: "Ieškoti produktų ar modelių…",
    filterSeries: "Produktų šeima",
    filterDescription: "Aprašymas",
    filterAllSeries: "Visos serijos",
    filterAllSeriesModels: "Visi serijų modeliai",
    filterModelRange: "Produktų serija",
    filterProductType: "Produktų serija",
    filterAny: "Bet kuris",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Ieškoti…",
    filterApply: "Filtruoti",
    filterReset: "Atstatyti",
    comingSoon: "Netrukus",
    technicalDetails: "Žiūrėti techninę informaciją",
    perfectusBadge: "Internetinis įrankis",
    perfectusCta: "PerfectusAir parinkimo įrankis",
    techLibrary: "Techninė biblioteka",
    viewAll: "Žiūrėti visus",
    catalogsTitle: "Produktų katalogai",
    guidesTitle: "Vadovai ir sertifikatai",
    sidebarSupportTitle: "Techninė pagalba",
    sidebarSupportDesc: "Susisiekite su mūsų inžinierių komanda dėl parinkimo, montavimo ir projektų konsultacijų.",
    sidebarSupportCta: "Prašyti pagalbos",
    topBarContact: "Kontaktai",
    topBarSettings: "Techninis centras",
    openMenu: "Atidaryti kategorijas",
    closeMenu: "Uždaryti",
    noResults: "Pagal jūsų filtrus produktų nerasta.",
    specFlow: "Maks. srautas",
    specPressure: "Slėgis",
    productNo: "Produkto Nr.",
    home: "Pradžia",
    products: "Produktai",
    docCatalogTitle: "{name} produktų katalogas",
    docGeneralCatalog: "NOVVES bendrasis produktų katalogas",
    docInstallManual: "Montavimo ir priežiūros vadovas",
    docDatasheets: "Techniniai duomenų lapai",
    modelsLabel: "modeliai",
    accessoryType: "Priedas",
    pageProductsSuffix: "gaminiai",
    allSolutions: "Žiūrėti visus sprendimus",
    specsTitle: "Techninės specifikacijos",
    galleryTitle: "Gaminio vaizdai",
    specSingular: "specifikacija",
    specPlural: "specifikacijos",
    tableTitle: "Modelių serija ir techniniai duomenys",
  },
  pl: {
    catalogTitle: "Katalog produktów",
    categoriesTitle: "Kategorie produktów",
    searchPlaceholder: "Szukaj produktów lub modeli…",
    filterSeries: "Rodzina produktów",
    filterDescription: "Opis",
    filterAllSeries: "Wszystkie serie",
    filterAllSeriesModels: "Wszystkie modele serii",
    filterModelRange: "Seria produktów",
    filterProductType: "Seria produktów",
    filterAny: "Dowolny",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Szukaj…",
    filterApply: "Filtruj",
    filterReset: "Resetuj",
    comingSoon: "Wkrótce",
    technicalDetails: "Zobacz szczegóły techniczne",
    perfectusBadge: "Narzędzie online",
    perfectusCta: "Narzędzie doboru PerfectusAir",
    techLibrary: "Biblioteka techniczna",
    viewAll: "Zobacz wszystko",
    catalogsTitle: "Katalogi produktów",
    guidesTitle: "Instrukcje i certyfikaty",
    sidebarSupportTitle: "Wsparcie techniczne",
    sidebarSupportDesc: "Skontaktuj się z naszym zespołem inżynierów w sprawie doboru, montażu i konsultacji projektowych.",
    sidebarSupportCta: "Poproś o wsparcie",
    topBarContact: "Kontakt",
    topBarSettings: "Centrum techniczne",
    openMenu: "Otwórz kategorie",
    closeMenu: "Zamknij",
    noResults: "Brak produktów spełniających kryteria filtrów.",
    specFlow: "Maks. przepływ",
    specPressure: "Ciśnienie",
    productNo: "Nr produktu",
    home: "Strona główna",
    products: "Produkty",
    docCatalogTitle: "Katalog produktów {name}",
    docGeneralCatalog: "Ogólny katalog produktów NOVVES",
    docInstallManual: "Instrukcja montażu i konserwacji",
    docDatasheets: "Karty katalogowe",
    modelsLabel: "modeli",
    accessoryType: "Akcesorium",
    pageProductsSuffix: "produkty",
    allSolutions: "Zobacz wszystkie rozwiązania",
    specsTitle: "Specyfikacja techniczna",
    galleryTitle: "Widoki produktu",
    specSingular: "specyfikacja",
    specPlural: "specyfikacje",
    tableTitle: "Seria modeli i dane techniczne",
  },
  ro: {
    catalogTitle: "Catalog de produse",
    categoriesTitle: "Categorii de produse",
    searchPlaceholder: "Căutați produse sau modele…",
    filterSeries: "Familie de produse",
    filterDescription: "Descriere",
    filterAllSeries: "Toate seriile",
    filterAllSeriesModels: "Toate modelele din serie",
    filterModelRange: "Serie de produse",
    filterProductType: "Serie de produse",
    filterAny: "Oricare",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Căutați…",
    filterApply: "Filtrează",
    filterReset: "Resetează",
    comingSoon: "În curând",
    technicalDetails: "Vedeți detaliile tehnice",
    perfectusBadge: "Instrument online",
    perfectusCta: "Instrument de selecție PerfectusAir",
    techLibrary: "Bibliotecă tehnică",
    viewAll: "Vedeți tot",
    catalogsTitle: "Cataloage de produse",
    guidesTitle: "Manuale și certificate",
    sidebarSupportTitle: "Asistență tehnică",
    sidebarSupportDesc: "Contactați echipa noastră de ingineri pentru selecție, instalare și consultanță de proiect.",
    sidebarSupportCta: "Solicitați asistență",
    topBarContact: "Contact",
    topBarSettings: "Centru tehnic",
    openMenu: "Deschideți categoriile",
    closeMenu: "Închideți",
    noResults: "Niciun produs nu corespunde filtrelor dvs.",
    specFlow: "Debit maxim",
    specPressure: "Presiune",
    productNo: "Nr. produs",
    home: "Acasă",
    products: "Produse",
    docCatalogTitle: "Catalog de produse {name}",
    docGeneralCatalog: "Catalog general de produse NOVVES",
    docInstallManual: "Manual de instalare și întreținere",
    docDatasheets: "Fișe tehnice",
    modelsLabel: "modele",
    accessoryType: "Accesoriu",
    pageProductsSuffix: "produse",
    allSolutions: "Vedeți toate soluțiile",
    specsTitle: "Specificații tehnice",
    galleryTitle: "Vizualizări ale produsului",
    specSingular: "specificație",
    specPlural: "specificații",
    tableTitle: "Serii de modele și date tehnice",
  },
  hu: {
    catalogTitle: "Termékkatalógus",
    categoriesTitle: "Termékkategóriák",
    searchPlaceholder: "Termékek vagy modellek keresése…",
    filterSeries: "Termékcsalád",
    filterDescription: "Leírás",
    filterAllSeries: "Összes sorozat",
    filterAllSeriesModels: "A sorozat összes modellje",
    filterModelRange: "Terméksorozat",
    filterProductType: "Terméksorozat",
    filterAny: "Bármely",
    filterMin: "Min",
    filterMax: "Max",
    searchPlaceholderShort: "Keresés…",
    filterApply: "Szűrés",
    filterReset: "Visszaállítás",
    comingSoon: "Hamarosan",
    technicalDetails: "Műszaki részletek megtekintése",
    perfectusBadge: "Online eszköz",
    perfectusCta: "PerfectusAir kiválasztó eszköz",
    techLibrary: "Műszaki könyvtár",
    viewAll: "Összes megtekintése",
    catalogsTitle: "Termékkatalógusok",
    guidesTitle: "Kézikönyvek és tanúsítványok",
    sidebarSupportTitle: "Műszaki támogatás",
    sidebarSupportDesc: "Vegye fel a kapcsolatot mérnöki csapatunkkal kiválasztással, telepítéssel és projekttanácsadással kapcsolatban.",
    sidebarSupportCta: "Támogatás kérése",
    topBarContact: "Kapcsolat",
    topBarSettings: "Műszaki központ",
    openMenu: "Kategóriák megnyitása",
    closeMenu: "Bezárás",
    noResults: "Egyetlen termék sem felel meg a szűrőknek.",
    specFlow: "Max. légszállítás",
    specPressure: "Nyomás",
    productNo: "Termékszám",
    home: "Főoldal",
    products: "Termékek",
    docCatalogTitle: "{name} termékkatalógus",
    docGeneralCatalog: "NOVVES általános termékkatalógus",
    docInstallManual: "Telepítési és karbantartási kézikönyv",
    docDatasheets: "Műszaki adatlapok",
    modelsLabel: "modell",
    accessoryType: "Tartozék",
    pageProductsSuffix: "termék",
    allSolutions: "Összes megoldás megtekintése",
    specsTitle: "Műszaki specifikációk",
    galleryTitle: "Terméknézetek",
    specSingular: "specifikáció",
    specPlural: "specifikációk",
    tableTitle: "Modellsorozatok és műszaki adatok",
  },
};

export function getProductCatalogUi(locale: Locale): ProductCatalogUi {
  return UI[locale] ?? UI.en;
}
