import type { Locale } from "@/i18n/config";

export type SolutionLibraryUi = {
  categoriesTitle: string;
  sidebarSupportTitle: string;
  sidebarSupportDesc: string;
  sidebarSupportCta: string;
  libraryTitle: string;
  libraryVersion: string;
  searchPlaceholder: string;
  searchClear: string;
  searchNoResults: string;
  searchGroupSolutions: string;
  searchGroupComponents: string;
  searchGroupDocuments: string;
  searchResultsHint: string;
  searchMore: string;
  searchMinChars: string;
  filter: string;
  filterTitle: string;
  filterContent: string;
  filterContentAll: string;
  filterContentProducts: string;
  filterContentDocuments: string;
  filterComponents: string;
  filterDocTypes: string;
  filterReset: string;
  filterActive: string;
  filterNoResults: string;
  filterDocPdf: string;
  filterDocDoc: string;
  filterDocBim: string;
  filterDocCert: string;
  topBarContact: string;
  topBarSettings: string;
  footerBrand: string;
  footerPrivacy: string;
  footerStandards: string;
  footerContact: string;
  solutions: string;
  expertQuote: string;
  emptyProducts: string;
  emptyDocs: string;
  docsComingSoon: string;
  coreComponents: string;
  viewCatalog: string;
  moreDetail: string;
  addToQuote: string;
  added: string;
  documentation: string;
  selections: string;
  projectInquiry: string;
  clear: string;
  quote: string;
  openMenu: string;
  closeMenu: string;
  sidebarHelp: string;
  sidebarTechnicalCenter: string;
  sidebarFireDetection: string;
  sidebarGasDetection: string;
  sidebarArchive: string;
  docCatalog: string;
  docGuidelines: string;
  docBim: string;
  docCert: string;
};

const UI: Record<Locale, SolutionLibraryUi> = {
  tr: {
    categoriesTitle: "Çözüm Kategorileri",
    sidebarSupportTitle: "Teknik destek",
    sidebarSupportDesc: "Seçim, montaj ve proje danışmanlığı için mühendislik ekibimizle iletişime geçin.",
    sidebarSupportCta: "Destek talebi",
    libraryTitle: "Teknik Kütüphane",
    libraryVersion: "V2.4 KURUMSAL",
    searchPlaceholder: "Çözüm, ürün veya doküman ara…",
    searchClear: "Aramayı temizle",
    searchNoResults: "“{query}” için sonuç bulunamadı.",
    searchGroupSolutions: "Çözümler",
    searchGroupComponents: "Bileşenler",
    searchGroupDocuments: "Dokümanlar",
    searchResultsHint: "{count} sonuç",
    searchMore: "+{count} sonuç daha — sol menüde",
    searchMinChars: "En az 2 karakter yazın",
    filter: "Filtre",
    filterTitle: "Filtrele",
    filterContent: "İçerik",
    filterContentAll: "Tümü",
    filterContentProducts: "Bileşenler",
    filterContentDocuments: "Dokümanlar",
    filterComponents: "Bileşen grupları",
    filterDocTypes: "Doküman tipi",
    filterReset: "Sıfırla",
    filterActive: "{count} filtre aktif",
    filterNoResults: "Seçili filtrelere uygun sonuç yok.",
    filterDocPdf: "PDF / Katalog",
    filterDocDoc: "Kılavuz",
    filterDocBim: "BIM",
    filterDocCert: "Sertifika",
    topBarContact: "İletişim",
    topBarSettings: "Teknik merkez",
    footerBrand: "Novves Çözümler",
    footerPrivacy: "Gizlilik",
    footerStandards: "Standartlar",
    footerContact: "İletişim",
    solutions: "Çözümler",
    expertQuote: "Teklif Alın",
    emptyProducts: "Bu çözüm için bileşen listesi henüz eklenmedi.",
    emptyDocs: "Yüklenebilir doküman bulunmuyor.",
    docsComingSoon: "Teknik dokümanlar yakında teknik merkezde yayınlanacak.",
    coreComponents: "Temel Bileşenler",
    viewCatalog: "Tüm Kataloğu Gör",
    moreDetail: "Detay",
    addToQuote: "Teklife Ekle",
    added: "Eklendi",
    documentation: "Dokümantasyon",
    selections: "Seçim",
    projectInquiry: "Proje Talebi",
    clear: "Temizle",
    quote: "Teklif",
    openMenu: "Menüyü aç",
    closeMenu: "Menüyü kapat",
    sidebarHelp: "Yardım Merkezi",
    sidebarTechnicalCenter: "Teknik Merkez",
    sidebarFireDetection: "Yangın Algılama",
    sidebarGasDetection: "Gaz Algılama",
    sidebarArchive: "Arşiv Kayıtları",
    docCatalog: "Teknik Katalog 2024",
    docGuidelines: "Tasarım Kılavuzu",
    docBim: "BIM / Revit Ailesi",
    docCert: "Sertifikalar ve Uygunluk",
  },
  en: {
    categoriesTitle: "Solution Categories",
    sidebarSupportTitle: "Technical support",
    sidebarSupportDesc: "Contact our engineering team for selection, installation and project consulting.",
    sidebarSupportCta: "Request support",
    libraryTitle: "Technical Library",
    libraryVersion: "V2.4 ENTERPRISE",
    searchPlaceholder: "Search solutions, products, or documents…",
    searchClear: "Clear search",
    searchNoResults: "No results for “{query}”.",
    searchGroupSolutions: "Solutions",
    searchGroupComponents: "Components",
    searchGroupDocuments: "Documents",
    searchResultsHint: "{count} results",
    searchMore: "+{count} more — see sidebar",
    searchMinChars: "Type at least 2 characters",
    filter: "Filter",
    filterTitle: "Filter",
    filterContent: "Content",
    filterContentAll: "All",
    filterContentProducts: "Components",
    filterContentDocuments: "Documents",
    filterComponents: "Component groups",
    filterDocTypes: "Document type",
    filterReset: "Reset",
    filterActive: "{count} filters active",
    filterNoResults: "No results match the selected filters.",
    filterDocPdf: "PDF / Catalog",
    filterDocDoc: "Guidelines",
    filterDocBim: "BIM",
    filterDocCert: "Certificates",
    topBarContact: "Contact",
    topBarSettings: "Technical center",
    footerBrand: "Novves Solutions",
    footerPrivacy: "Privacy",
    footerStandards: "Standards",
    footerContact: "Contact",
    solutions: "Solutions",
    expertQuote: "Get a Quote",
    emptyProducts: "Component list for this solution is not available yet.",
    emptyDocs: "No downloadable documents available.",
    docsComingSoon: "Technical documents will be published in the technical center soon.",
    coreComponents: "Core Components",
    viewCatalog: "View Entire Catalog",
    moreDetail: "More Detail",
    addToQuote: "Add to Quote",
    added: "Added",
    documentation: "Documentation",
    selections: "Selection(s)",
    projectInquiry: "Project Inquiry",
    clear: "Clear",
    quote: "Quote",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    sidebarHelp: "Help Center",
    sidebarTechnicalCenter: "Technical Center",
    sidebarFireDetection: "Fire Detection",
    sidebarGasDetection: "Gas Detection",
    sidebarArchive: "Archive Records",
    docCatalog: "Technical Catalog 2024",
    docGuidelines: "Design Guidelines",
    docBim: "BIM / Revit Family",
    docCert: "Certificates & Compliance",
  },
  ru: {
    categoriesTitle: "Категории решений",
    sidebarSupportTitle: "Техническая поддержка",
    sidebarSupportDesc: "Свяжитесь с нашей инженерной командой для подбора, монтажа и проектного консалтинга.",
    sidebarSupportCta: "Запросить поддержку",
    libraryTitle: "Техническая библиотека",
    libraryVersion: "V2.4 КОРПОРАТИВНАЯ",
    searchPlaceholder: "Поиск решений, продуктов или документов…",
    searchClear: "Очистить поиск",
    searchNoResults: "Нет результатов по запросу “{query}”.",
    searchGroupSolutions: "Решения",
    searchGroupComponents: "Компоненты",
    searchGroupDocuments: "Документы",
    searchResultsHint: "{count} результатов",
    searchMore: "+{count} ещё — в боковом меню",
    searchMinChars: "Введите не менее 2 символов",
    filter: "Фильтр",
    filterTitle: "Фильтровать",
    filterContent: "Содержимое",
    filterContentAll: "Все",
    filterContentProducts: "Компоненты",
    filterContentDocuments: "Документы",
    filterComponents: "Группы компонентов",
    filterDocTypes: "Тип документа",
    filterReset: "Сбросить",
    filterActive: "Активно фильтров: {count}",
    filterNoResults: "Нет результатов по выбранным фильтрам.",
    filterDocPdf: "PDF / Каталог",
    filterDocDoc: "Руководство",
    filterDocBim: "BIM",
    filterDocCert: "Сертификаты",
    topBarContact: "Контакты",
    topBarSettings: "Технический центр",
    footerBrand: "Novves Решения",
    footerPrivacy: "Конфиденциальность",
    footerStandards: "Стандарты",
    footerContact: "Контакты",
    solutions: "Решения",
    expertQuote: "Получить предложение",
    emptyProducts: "Список компонентов для этого решения пока не добавлен.",
    emptyDocs: "Нет документов для загрузки.",
    docsComingSoon: "Техническая документация скоро будет опубликована в техническом центре.",
    coreComponents: "Основные компоненты",
    viewCatalog: "Смотреть весь каталог",
    moreDetail: "Подробнее",
    addToQuote: "Добавить в запрос",
    added: "Добавлено",
    documentation: "Документация",
    selections: "Выбор",
    projectInquiry: "Запрос по проекту",
    clear: "Очистить",
    quote: "Запрос",
    openMenu: "Открыть меню",
    closeMenu: "Закрыть меню",
    sidebarHelp: "Центр помощи",
    sidebarTechnicalCenter: "Технический центр",
    sidebarFireDetection: "Обнаружение пожара",
    sidebarGasDetection: "Обнаружение газа",
    sidebarArchive: "Архивные записи",
    docCatalog: "Технический каталог 2024",
    docGuidelines: "Руководство по проектированию",
    docBim: "BIM / Семейство Revit",
    docCert: "Сертификаты и соответствие",
  },
  ar: {
    categoriesTitle: "فئات الحلول",
    sidebarSupportTitle: "الدعم الفني",
    sidebarSupportDesc: "تواصل مع فريقنا الهندسي للحصول على الدعم في الاختيار والتركيب والاستشارات المشاريعية.",
    sidebarSupportCta: "طلب الدعم",
    libraryTitle: "المكتبة الفنية",
    libraryVersion: "V2.4 للمؤسسات",
    searchPlaceholder: "ابحث عن الحلول أو المنتجات أو المستندات…",
    searchClear: "مسح البحث",
    searchNoResults: "لا توجد نتائج لـ “{query}”.",
    searchGroupSolutions: "الحلول",
    searchGroupComponents: "المكوّنات",
    searchGroupDocuments: "المستندات",
    searchResultsHint: "{count} نتيجة",
    searchMore: "+{count} نتيجة إضافية — انظر الشريط الجانبي",
    searchMinChars: "اكتب حرفين على الأقل",
    filter: "تصفية",
    filterTitle: "تصفية",
    filterContent: "المحتوى",
    filterContentAll: "الكل",
    filterContentProducts: "المكوّنات",
    filterContentDocuments: "المستندات",
    filterComponents: "مجموعات المكوّنات",
    filterDocTypes: "نوع المستند",
    filterReset: "إعادة تعيين",
    filterActive: "{count} عامل تصفية نشط",
    filterNoResults: "لا توجد نتائج تطابق عوامل التصفية المحددة.",
    filterDocPdf: "PDF / كتالوج",
    filterDocDoc: "إرشادات",
    filterDocBim: "BIM",
    filterDocCert: "شهادات",
    topBarContact: "اتصل بنا",
    topBarSettings: "المركز الفني",
    footerBrand: "حلول Novves",
    footerPrivacy: "الخصوصية",
    footerStandards: "المعايير",
    footerContact: "اتصل بنا",
    solutions: "الحلول",
    expertQuote: "احصل على عرض سعر",
    emptyProducts: "قائمة المكوّنات لهذا الحل غير متوفرة بعد.",
    emptyDocs: "لا توجد مستندات قابلة للتنزيل.",
    docsComingSoon: "ستُنشر المستندات الفنية في المركز الفني قريبًا.",
    coreComponents: "المكوّنات الأساسية",
    viewCatalog: "عرض الكتالوج بالكامل",
    moreDetail: "مزيد من التفاصيل",
    addToQuote: "إضافة إلى عرض السعر",
    added: "تمت الإضافة",
    documentation: "التوثيق",
    selections: "اختيار",
    projectInquiry: "استفسار عن مشروع",
    clear: "مسح",
    quote: "عرض السعر",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    sidebarHelp: "مركز المساعدة",
    sidebarTechnicalCenter: "المركز الفني",
    sidebarFireDetection: "كشف الحرائق",
    sidebarGasDetection: "كشف الغاز",
    sidebarArchive: "سجلات الأرشيف",
    docCatalog: "الكتالوج الفني 2024",
    docGuidelines: "دليل التصميم",
    docBim: "BIM / عائلة Revit",
    docCert: "الشهادات والامتثال",
  },
  de: {
    categoriesTitle: "Lösungskategorien",
    sidebarSupportTitle: "Technischer Support",
    sidebarSupportDesc: "Kontaktieren Sie unser Engineering-Team für Auswahl, Montage und Projektberatung.",
    sidebarSupportCta: "Support anfragen",
    libraryTitle: "Technische Bibliothek",
    libraryVersion: "V2.4 ENTERPRISE",
    searchPlaceholder: "Lösungen, Produkte oder Dokumente suchen…",
    searchClear: "Suche zurücksetzen",
    searchNoResults: "Keine Ergebnisse für „{query}“.",
    searchGroupSolutions: "Lösungen",
    searchGroupComponents: "Komponenten",
    searchGroupDocuments: "Dokumente",
    searchResultsHint: "{count} Ergebnisse",
    searchMore: "+{count} weitere — siehe Seitenleiste",
    searchMinChars: "Mindestens 2 Zeichen eingeben",
    filter: "Filter",
    filterTitle: "Filtern",
    filterContent: "Inhalt",
    filterContentAll: "Alle",
    filterContentProducts: "Komponenten",
    filterContentDocuments: "Dokumente",
    filterComponents: "Komponentengruppen",
    filterDocTypes: "Dokumenttyp",
    filterReset: "Zurücksetzen",
    filterActive: "{count} Filter aktiv",
    filterNoResults: "Keine Ergebnisse für die ausgewählten Filter.",
    filterDocPdf: "PDF / Katalog",
    filterDocDoc: "Richtlinien",
    filterDocBim: "BIM",
    filterDocCert: "Zertifikate",
    topBarContact: "Kontakt",
    topBarSettings: "Technikzentrum",
    footerBrand: "Novves Lösungen",
    footerPrivacy: "Datenschutz",
    footerStandards: "Normen",
    footerContact: "Kontakt",
    solutions: "Lösungen",
    expertQuote: "Angebot anfordern",
    emptyProducts: "Die Komponentenliste für diese Lösung ist noch nicht verfügbar.",
    emptyDocs: "Keine herunterladbaren Dokumente verfügbar.",
    docsComingSoon: "Technische Dokumente werden in Kürze im Technikzentrum veröffentlicht.",
    coreComponents: "Kernkomponenten",
    viewCatalog: "Gesamten Katalog ansehen",
    moreDetail: "Mehr Details",
    addToQuote: "Zum Angebot hinzufügen",
    added: "Hinzugefügt",
    documentation: "Dokumentation",
    selections: "Auswahl",
    projectInquiry: "Projektanfrage",
    clear: "Leeren",
    quote: "Angebot",
    openMenu: "Menü öffnen",
    closeMenu: "Menü schließen",
    sidebarHelp: "Hilfecenter",
    sidebarTechnicalCenter: "Technikzentrum",
    sidebarFireDetection: "Branderkennung",
    sidebarGasDetection: "Gaserkennung",
    sidebarArchive: "Archivaufzeichnungen",
    docCatalog: "Technischer Katalog 2024",
    docGuidelines: "Designrichtlinien",
    docBim: "BIM / Revit-Familie",
    docCert: "Zertifikate & Konformität",
  },
  it: {
    categoriesTitle: "Categorie di soluzioni",
    sidebarSupportTitle: "Supporto tecnico",
    sidebarSupportDesc: "Contatta il nostro team di ingegneria per selezione, installazione e consulenza di progetto.",
    sidebarSupportCta: "Richiedi assistenza",
    libraryTitle: "Libreria tecnica",
    libraryVersion: "V2.4 ENTERPRISE",
    searchPlaceholder: "Cerca soluzioni, prodotti o documenti…",
    searchClear: "Cancella ricerca",
    searchNoResults: "Nessun risultato per “{query}”.",
    searchGroupSolutions: "Soluzioni",
    searchGroupComponents: "Componenti",
    searchGroupDocuments: "Documenti",
    searchResultsHint: "{count} risultati",
    searchMore: "+{count} in più — vedi barra laterale",
    searchMinChars: "Digita almeno 2 caratteri",
    filter: "Filtro",
    filterTitle: "Filtra",
    filterContent: "Contenuto",
    filterContentAll: "Tutti",
    filterContentProducts: "Componenti",
    filterContentDocuments: "Documenti",
    filterComponents: "Gruppi di componenti",
    filterDocTypes: "Tipo di documento",
    filterReset: "Reimposta",
    filterActive: "{count} filtri attivi",
    filterNoResults: "Nessun risultato corrisponde ai filtri selezionati.",
    filterDocPdf: "PDF / Catalogo",
    filterDocDoc: "Linee guida",
    filterDocBim: "BIM",
    filterDocCert: "Certificati",
    topBarContact: "Contatti",
    topBarSettings: "Centro tecnico",
    footerBrand: "Novves Solutions",
    footerPrivacy: "Privacy",
    footerStandards: "Standard",
    footerContact: "Contatti",
    solutions: "Soluzioni",
    expertQuote: "Richiedi un preventivo",
    emptyProducts: "L'elenco dei componenti per questa soluzione non è ancora disponibile.",
    emptyDocs: "Nessun documento scaricabile disponibile.",
    docsComingSoon: "I documenti tecnici saranno presto pubblicati nel centro tecnico.",
    coreComponents: "Componenti principali",
    viewCatalog: "Visualizza l'intero catalogo",
    moreDetail: "Maggiori dettagli",
    addToQuote: "Aggiungi al preventivo",
    added: "Aggiunto",
    documentation: "Documentazione",
    selections: "Selezione/i",
    projectInquiry: "Richiesta di progetto",
    clear: "Cancella",
    quote: "Preventivo",
    openMenu: "Apri menu",
    closeMenu: "Chiudi menu",
    sidebarHelp: "Centro assistenza",
    sidebarTechnicalCenter: "Centro tecnico",
    sidebarFireDetection: "Rilevamento incendi",
    sidebarGasDetection: "Rilevamento gas",
    sidebarArchive: "Registri di archivio",
    docCatalog: "Catalogo tecnico 2024",
    docGuidelines: "Linee guida di progettazione",
    docBim: "BIM / Famiglia Revit",
    docCert: "Certificati e conformità",
  },
  fr: {
    categoriesTitle: "Catégories de solutions",
    sidebarSupportTitle: "Support technique",
    sidebarSupportDesc: "Contactez notre équipe d’ingénierie pour la sélection, l’installation et le conseil projet.",
    sidebarSupportCta: "Demander un support",
    libraryTitle: "Bibliothèque technique",
    libraryVersion: "V2.4 ENTREPRISE",
    searchPlaceholder: "Rechercher solutions, produits ou documents…",
    searchClear: "Effacer la recherche",
    searchNoResults: "Aucun résultat pour “{query}”.",
    searchGroupSolutions: "Solutions",
    searchGroupComponents: "Composants",
    searchGroupDocuments: "Documents",
    searchResultsHint: "{count} résultats",
    searchMore: "+{count} de plus — voir le menu latéral",
    searchMinChars: "Saisissez au moins 2 caractères",
    filter: "Filtre",
    filterTitle: "Filtrer",
    filterContent: "Contenu",
    filterContentAll: "Tout",
    filterContentProducts: "Composants",
    filterContentDocuments: "Documents",
    filterComponents: "Groupes de composants",
    filterDocTypes: "Type de document",
    filterReset: "Réinitialiser",
    filterActive: "{count} filtres actifs",
    filterNoResults: "Aucun résultat ne correspond aux filtres sélectionnés.",
    filterDocPdf: "PDF / Catalogue",
    filterDocDoc: "Guide",
    filterDocBim: "BIM",
    filterDocCert: "Certificats",
    topBarContact: "Contact",
    topBarSettings: "Centre technique",
    footerBrand: "Novves Solutions",
    footerPrivacy: "Confidentialité",
    footerStandards: "Normes",
    footerContact: "Contact",
    solutions: "Solutions",
    expertQuote: "Demander un devis",
    emptyProducts: "La liste des composants pour cette solution n’est pas encore disponible.",
    emptyDocs: "Aucun document téléchargeable disponible.",
    docsComingSoon: "Les documents techniques seront bientôt publiés dans le centre technique.",
    coreComponents: "Composants principaux",
    viewCatalog: "Voir tout le catalogue",
    moreDetail: "Plus de détails",
    addToQuote: "Ajouter au devis",
    added: "Ajouté",
    documentation: "Documentation",
    selections: "Sélection(s)",
    projectInquiry: "Demande de projet",
    clear: "Effacer",
    quote: "Devis",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    sidebarHelp: "Centre d’aide",
    sidebarTechnicalCenter: "Centre technique",
    sidebarFireDetection: "Détection incendie",
    sidebarGasDetection: "Détection de gaz",
    sidebarArchive: "Archives",
    docCatalog: "Catalogue technique 2024",
    docGuidelines: "Guide de conception",
    docBim: "Famille BIM / Revit",
    docCert: "Certificats et conformité",
  },
  az: {
    categoriesTitle: "Həll Kateqoriyaları",
    sidebarSupportTitle: "Texniki dəstək",
    sidebarSupportDesc: "Seçim, montaj və layihə məsləhəti üçün mühəndislik komandamızla əlaqə saxlayın.",
    sidebarSupportCta: "Dəstək tələbi",
    libraryTitle: "Texniki Kitabxana",
    libraryVersion: "V2.4 KORPORATİV",
    searchPlaceholder: "Həll, məhsul və ya sənəd axtar…",
    searchClear: "Axtarışı təmizlə",
    searchNoResults: "“{query}” üçün nəticə tapılmadı.",
    searchGroupSolutions: "Həllər",
    searchGroupComponents: "Komponentlər",
    searchGroupDocuments: "Sənədlər",
    searchResultsHint: "{count} nəticə",
    searchMore: "+{count} nəticə daha — yan menyuda",
    searchMinChars: "Ən azı 2 simvol yazın",
    filter: "Filtr",
    filterTitle: "Filtrlə",
    filterContent: "Məzmun",
    filterContentAll: "Hamısı",
    filterContentProducts: "Komponentlər",
    filterContentDocuments: "Sənədlər",
    filterComponents: "Komponent qrupları",
    filterDocTypes: "Sənəd növü",
    filterReset: "Sıfırla",
    filterActive: "{count} filtr aktiv",
    filterNoResults: "Seçilmiş filtrlərə uyğun nəticə yoxdur.",
    filterDocPdf: "PDF / Kataloq",
    filterDocDoc: "Təlimat",
    filterDocBim: "BIM",
    filterDocCert: "Sertifikat",
    topBarContact: "Əlaqə",
    topBarSettings: "Texniki mərkəz",
    footerBrand: "Novves Həllər",
    footerPrivacy: "Məxfilik",
    footerStandards: "Standartlar",
    footerContact: "Əlaqə",
    solutions: "Həllər",
    expertQuote: "Təklif Alın",
    emptyProducts: "Bu həll üçün komponent siyahısı hələ əlavə edilməyib.",
    emptyDocs: "Yüklənə bilən sənəd yoxdur.",
    docsComingSoon: "Texniki sənədlər tezliklə texniki mərkəzdə yayımlanacaq.",
    coreComponents: "Əsas Komponentlər",
    viewCatalog: "Bütün Kataloqa Bax",
    moreDetail: "Ətraflı",
    addToQuote: "Təklifə Əlavə Et",
    added: "Əlavə edildi",
    documentation: "Sənədləşdirmə",
    selections: "Seçim",
    projectInquiry: "Layihə Tələbi",
    clear: "Təmizlə",
    quote: "Təklif",
    openMenu: "Menyunu aç",
    closeMenu: "Menyunu bağla",
    sidebarHelp: "Yardım Mərkəzi",
    sidebarTechnicalCenter: "Texniki Mərkəz",
    sidebarFireDetection: "Yanğın Aşkarlanması",
    sidebarGasDetection: "Qaz Aşkarlanması",
    sidebarArchive: "Arxiv Qeydləri",
    docCatalog: "Texniki Kataloq 2024",
    docGuidelines: "Dizayn Təlimatı",
    docBim: "BIM / Revit Ailəsi",
    docCert: "Sertifikatlar və Uyğunluq",
  },
  kk: {
    categoriesTitle: "Шешім санаттары",
    sidebarSupportTitle: "Техникалық қолдау",
    sidebarSupportDesc: "Таңдау, монтаж және жоба бойынша кеңес алу үшін инженерлік тобымызбен байланысыңыз.",
    sidebarSupportCta: "Қолдау сұрау",
    libraryTitle: "Техникалық кітапхана",
    libraryVersion: "V2.4 КОРПОРАТИВТІК",
    searchPlaceholder: "Шешім, өнім немесе құжат іздеу…",
    searchClear: "Іздеуді тазалау",
    searchNoResults: "“{query}” бойынша нәтиже табылмады.",
    searchGroupSolutions: "Шешімдер",
    searchGroupComponents: "Компоненттер",
    searchGroupDocuments: "Құжаттар",
    searchResultsHint: "{count} нәтиже",
    searchMore: "+{count} нәтиже — бүйір мәзірден қараңыз",
    searchMinChars: "Кемінде 2 таңба теріңіз",
    filter: "Сүзгі",
    filterTitle: "Сүзу",
    filterContent: "Мазмұн",
    filterContentAll: "Барлығы",
    filterContentProducts: "Компоненттер",
    filterContentDocuments: "Құжаттар",
    filterComponents: "Компонент топтары",
    filterDocTypes: "Құжат түрі",
    filterReset: "Қалпына келтіру",
    filterActive: "{count} сүзгі белсенді",
    filterNoResults: "Таңдалған сүзгілерге сәйкес нәтиже жоқ.",
    filterDocPdf: "PDF / Каталог",
    filterDocDoc: "Нұсқаулық",
    filterDocBim: "BIM",
    filterDocCert: "Сертификаттар",
    topBarContact: "Байланыс",
    topBarSettings: "Техникалық орталық",
    footerBrand: "Novves шешімдері",
    footerPrivacy: "Құпиялылық",
    footerStandards: "Стандарттар",
    footerContact: "Байланыс",
    solutions: "Шешімдер",
    expertQuote: "Баға сұрау",
    emptyProducts: "Бұл шешім үшін компоненттер тізімі әзірге қосылмаған.",
    emptyDocs: "Жүктеуге болатын құжаттар жоқ.",
    docsComingSoon: "Техникалық құжаттар жақын арада техникалық орталықта жарияланады.",
    coreComponents: "Негізгі компоненттер",
    viewCatalog: "Толық каталогты қарау",
    moreDetail: "Толығырақ",
    addToQuote: "Бағаға қосу",
    added: "Қосылды",
    documentation: "Құжаттама",
    selections: "Таңдау",
    projectInquiry: "Жоба сұрауы",
    clear: "Тазалау",
    quote: "Баға",
    openMenu: "Мәзірді ашу",
    closeMenu: "Мәзірді жабу",
    sidebarHelp: "Көмек орталығы",
    sidebarTechnicalCenter: "Техникалық орталық",
    sidebarFireDetection: "Өрт анықтау",
    sidebarGasDetection: "Газ анықтау",
    sidebarArchive: "Мұрағат жазбалары",
    docCatalog: "Техникалық каталог 2024",
    docGuidelines: "Жобалау нұсқаулығы",
    docBim: "BIM / Revit отбасы",
    docCert: "Сертификаттар және сәйкестік",
  },
  tg: {
    categoriesTitle: "Категорияҳои ҳалли масъала",
    sidebarSupportTitle: "Дастгирии техникӣ",
    sidebarSupportDesc: "Барои интихоб, насб ва машварати лоиҳавӣ бо гурӯҳи муҳандисии мо тамос гиред.",
    sidebarSupportCta: "Дархости дастгирӣ",
    libraryTitle: "Китобхонаи техникӣ",
    libraryVersion: "V2.4 КОРПОРАТИВӢ",
    searchPlaceholder: "Ҷустуҷӯи ҳалли масъала, маҳсулот ё ҳуҷҷат…",
    searchClear: "Тоза кардани ҷустуҷӯ",
    searchNoResults: "Барои “{query}” натиҷае ёфт нашуд.",
    searchGroupSolutions: "Ҳалли масъалаҳо",
    searchGroupComponents: "Ҷузъҳо",
    searchGroupDocuments: "Ҳуҷҷатҳо",
    searchResultsHint: "{count} натиҷа",
    searchMore: "+{count} натиҷаи дигар — дар менюи паҳлӯӣ",
    searchMinChars: "Камаш 2 ҳарф ворид кунед",
    filter: "Филтр",
    filterTitle: "Филтр кардан",
    filterContent: "Мундариҷа",
    filterContentAll: "Ҳама",
    filterContentProducts: "Ҷузъҳо",
    filterContentDocuments: "Ҳуҷҷатҳо",
    filterComponents: "Гурӯҳҳои ҷузъҳо",
    filterDocTypes: "Намуди ҳуҷҷат",
    filterReset: "Аз нав танзим",
    filterActive: "{count} филтр фаъол",
    filterNoResults: "Ба филтрҳои интихобшуда натиҷае мувофиқ нест.",
    filterDocPdf: "PDF / Каталог",
    filterDocDoc: "Дастур",
    filterDocBim: "BIM",
    filterDocCert: "Сертификатҳо",
    topBarContact: "Тамос",
    topBarSettings: "Маркази техникӣ",
    footerBrand: "Novves Ҳалли масъалаҳо",
    footerPrivacy: "Махфият",
    footerStandards: "Стандартҳо",
    footerContact: "Тамос",
    solutions: "Ҳалли масъалаҳо",
    expertQuote: "Гирифтани таклиф",
    emptyProducts: "Рӯйхати ҷузъҳо барои ин ҳалли масъала ҳанӯз илова нашудааст.",
    emptyDocs: "Ҳуҷҷати боргиришаванда мавҷуд нест.",
    docsComingSoon: "Ҳуҷҷатҳои техникӣ ба зудӣ дар маркази техникӣ нашр мешаванд.",
    coreComponents: "Ҷузъҳои асосӣ",
    viewCatalog: "Дидани тамоми каталог",
    moreDetail: "Тафсилот",
    addToQuote: "Илова ба таклиф",
    added: "Илова шуд",
    documentation: "Ҳуҷҷатнигорӣ",
    selections: "Интихоб",
    projectInquiry: "Дархости лоиҳа",
    clear: "Тоза кардан",
    quote: "Таклиф",
    openMenu: "Кушодани меню",
    closeMenu: "Бастани меню",
    sidebarHelp: "Маркази кӯмак",
    sidebarTechnicalCenter: "Маркази техникӣ",
    sidebarFireDetection: "Муайянкунии сӯхтор",
    sidebarGasDetection: "Муайянкунии газ",
    sidebarArchive: "Сабтҳои бойгонӣ",
    docCatalog: "Каталоги техникии 2024",
    docGuidelines: "Дастури тарроҳӣ",
    docBim: "BIM / Оилаи Revit",
    docCert: "Сертификатҳо ва мутобиқат",
  },
  es: {
    categoriesTitle: "Categorías de soluciones",
    sidebarSupportTitle: "Soporte técnico",
    sidebarSupportDesc: "Contacte con nuestro equipo de ingeniería para selección, instalación y asesoría de proyectos.",
    sidebarSupportCta: "Solicitar soporte",
    libraryTitle: "Biblioteca técnica",
    libraryVersion: "V2.4 ENTERPRISE",
    searchPlaceholder: "Buscar soluciones, productos o documentos…",
    searchClear: "Borrar búsqueda",
    searchNoResults: "Sin resultados para “{query}”.",
    searchGroupSolutions: "Soluciones",
    searchGroupComponents: "Componentes",
    searchGroupDocuments: "Documentos",
    searchResultsHint: "{count} resultados",
    searchMore: "+{count} resultados más — en el menú lateral",
    searchMinChars: "Escriba al menos 2 caracteres",
    filter: "Filtro",
    filterTitle: "Filtrar",
    filterContent: "Contenido",
    filterContentAll: "Todos",
    filterContentProducts: "Componentes",
    filterContentDocuments: "Documentos",
    filterComponents: "Grupos de componentes",
    filterDocTypes: "Tipo de documento",
    filterReset: "Restablecer",
    filterActive: "{count} filtros activos",
    filterNoResults: "Ningún resultado coincide con los filtros seleccionados.",
    filterDocPdf: "PDF / Catálogo",
    filterDocDoc: "Guías",
    filterDocBim: "BIM",
    filterDocCert: "Certificados",
    topBarContact: "Contacto",
    topBarSettings: "Centro técnico",
    footerBrand: "Novves Soluciones",
    footerPrivacy: "Privacidad",
    footerStandards: "Normas",
    footerContact: "Contacto",
    solutions: "Soluciones",
    expertQuote: "Solicitar presupuesto",
    emptyProducts: "La lista de componentes para esta solución aún no está disponible.",
    emptyDocs: "No hay documentos descargables disponibles.",
    docsComingSoon: "Los documentos técnicos se publicarán próximamente en el centro técnico.",
    coreComponents: "Componentes principales",
    viewCatalog: "Ver todo el catálogo",
    moreDetail: "Más detalles",
    addToQuote: "Añadir al presupuesto",
    added: "Añadido",
    documentation: "Documentación",
    selections: "Selección(es)",
    projectInquiry: "Consulta de proyecto",
    clear: "Borrar",
    quote: "Presupuesto",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
    sidebarHelp: "Centro de ayuda",
    sidebarTechnicalCenter: "Centro técnico",
    sidebarFireDetection: "Detección de incendios",
    sidebarGasDetection: "Detección de gases",
    sidebarArchive: "Registros de archivo",
    docCatalog: "Catálogo técnico 2024",
    docGuidelines: "Guía de diseño",
    docBim: "BIM / Familia Revit",
    docCert: "Certificados y conformidad",
  },
  zh: {
    categoriesTitle: "解决方案分类",
    sidebarSupportTitle: "技术支持",
    sidebarSupportDesc: "如需选型、安装及项目咨询，请联系我们的工程团队。",
    sidebarSupportCta: "申请支持",
    libraryTitle: "技术库",
    libraryVersion: "V2.4 企业版",
    searchPlaceholder: "搜索解决方案、产品或文档…",
    searchClear: "清除搜索",
    searchNoResults: "未找到与“{query}”相关的结果。",
    searchGroupSolutions: "解决方案",
    searchGroupComponents: "组件",
    searchGroupDocuments: "文档",
    searchResultsHint: "{count} 条结果",
    searchMore: "另有 {count} 条结果 — 见侧边栏",
    searchMinChars: "请至少输入 2 个字符",
    filter: "筛选",
    filterTitle: "筛选",
    filterContent: "内容",
    filterContentAll: "全部",
    filterContentProducts: "组件",
    filterContentDocuments: "文档",
    filterComponents: "组件分组",
    filterDocTypes: "文档类型",
    filterReset: "重置",
    filterActive: "已启用 {count} 个筛选条件",
    filterNoResults: "没有符合所选筛选条件的结果。",
    filterDocPdf: "PDF / 样本",
    filterDocDoc: "技术导则",
    filterDocBim: "BIM",
    filterDocCert: "证书",
    topBarContact: "联系我们",
    topBarSettings: "技术中心",
    footerBrand: "Novves 解决方案",
    footerPrivacy: "隐私",
    footerStandards: "标准规范",
    footerContact: "联系我们",
    solutions: "解决方案",
    expertQuote: "获取报价",
    emptyProducts: "该解决方案的组件清单尚未提供。",
    emptyDocs: "暂无可下载的文档。",
    docsComingSoon: "技术文档即将在技术中心发布。",
    coreComponents: "核心组件",
    viewCatalog: "查看完整样本",
    moreDetail: "更多详情",
    addToQuote: "加入报价",
    added: "已添加",
    documentation: "技术文档",
    selections: "已选项",
    projectInquiry: "项目咨询",
    clear: "清除",
    quote: "报价",
    openMenu: "打开菜单",
    closeMenu: "关闭菜单",
    sidebarHelp: "帮助中心",
    sidebarTechnicalCenter: "技术中心",
    sidebarFireDetection: "火灾探测",
    sidebarGasDetection: "气体探测",
    sidebarArchive: "归档记录",
    docCatalog: "2024 技术样本",
    docGuidelines: "设计导则",
    docBim: "BIM / Revit 族文件",
    docCert: "证书与合规",
  },
  ur: {
    categoriesTitle: "حل کی اقسام",
    sidebarSupportTitle: "تکنیکی معاونت",
    sidebarSupportDesc: "انتخاب، تنصیب اور پروجیکٹ مشاورت کے لیے ہماری انجینئرنگ ٹیم سے رابطہ کریں۔",
    sidebarSupportCta: "معاونت کی درخواست",
    libraryTitle: "تکنیکی لائبریری",
    libraryVersion: "V2.4 انٹرپرائز",
    searchPlaceholder: "حل، مصنوعات یا دستاویزات تلاش کریں…",
    searchClear: "تلاش صاف کریں",
    searchNoResults: "“{query}” کے لیے کوئی نتیجہ نہیں ملا۔",
    searchGroupSolutions: "حل",
    searchGroupComponents: "اجزاء",
    searchGroupDocuments: "دستاویزات",
    searchResultsHint: "{count} نتائج",
    searchMore: "+{count} مزید — سائیڈبار میں دیکھیں",
    searchMinChars: "کم از کم 2 حروف لکھیں",
    filter: "فلٹر",
    filterTitle: "فلٹر کریں",
    filterContent: "مواد",
    filterContentAll: "تمام",
    filterContentProducts: "اجزاء",
    filterContentDocuments: "دستاویزات",
    filterComponents: "اجزاء کے گروپ",
    filterDocTypes: "دستاویز کی قسم",
    filterReset: "ری سیٹ کریں",
    filterActive: "{count} فلٹر فعال",
    filterNoResults: "منتخب فلٹرز سے کوئی نتیجہ مطابقت نہیں رکھتا۔",
    filterDocPdf: "PDF / کیٹلاگ",
    filterDocDoc: "ہدایات",
    filterDocBim: "BIM",
    filterDocCert: "سرٹیفکیٹس",
    topBarContact: "رابطہ",
    topBarSettings: "تکنیکی مرکز",
    footerBrand: "Novves حل",
    footerPrivacy: "رازداری",
    footerStandards: "معیارات",
    footerContact: "رابطہ",
    solutions: "حل",
    expertQuote: "قیمت کا تخمینہ حاصل کریں",
    emptyProducts: "اس حل کے لیے اجزاء کی فہرست ابھی دستیاب نہیں ہے۔",
    emptyDocs: "کوئی قابلِ ڈاؤن لوڈ دستاویز دستیاب نہیں۔",
    docsComingSoon: "تکنیکی دستاویزات جلد تکنیکی مرکز میں شائع کی جائیں گی۔",
    coreComponents: "بنیادی اجزاء",
    viewCatalog: "مکمل کیٹلاگ دیکھیں",
    moreDetail: "مزید تفصیل",
    addToQuote: "تخمینے میں شامل کریں",
    added: "شامل کر دیا گیا",
    documentation: "دستاویزات",
    selections: "انتخاب",
    projectInquiry: "پروجیکٹ استفسار",
    clear: "صاف کریں",
    quote: "تخمینہ",
    openMenu: "مینو کھولیں",
    closeMenu: "مینو بند کریں",
    sidebarHelp: "مدد مرکز",
    sidebarTechnicalCenter: "تکنیکی مرکز",
    sidebarFireDetection: "آگ کی شناخت",
    sidebarGasDetection: "گیس کی شناخت",
    sidebarArchive: "آرکائیو ریکارڈز",
    docCatalog: "تکنیکی کیٹلاگ 2024",
    docGuidelines: "ڈیزائن ہدایات",
    docBim: "BIM / Revit فیملی",
    docCert: "سرٹیفکیٹس اور تعمیل",
  },
  lt: {
    categoriesTitle: "Sprendimų kategorijos",
    sidebarSupportTitle: "Techninė pagalba",
    sidebarSupportDesc: "Susisiekite su mūsų inžinierių komanda dėl parinkimo, montavimo ir projektavimo konsultacijų.",
    sidebarSupportCta: "Prašyti pagalbos",
    libraryTitle: "Techninė biblioteka",
    libraryVersion: "V2.4 ENTERPRISE",
    searchPlaceholder: "Ieškoti sprendimų, gaminių ar dokumentų…",
    searchClear: "Išvalyti paiešką",
    searchNoResults: "Pagal „{query}“ rezultatų nerasta.",
    searchGroupSolutions: "Sprendimai",
    searchGroupComponents: "Komponentai",
    searchGroupDocuments: "Dokumentai",
    searchResultsHint: "{count} rezultatų",
    searchMore: "+{count} dar — žr. šoninį meniu",
    searchMinChars: "Įveskite bent 2 simbolius",
    filter: "Filtras",
    filterTitle: "Filtruoti",
    filterContent: "Turinys",
    filterContentAll: "Visi",
    filterContentProducts: "Komponentai",
    filterContentDocuments: "Dokumentai",
    filterComponents: "Komponentų grupės",
    filterDocTypes: "Dokumento tipas",
    filterReset: "Atstatyti",
    filterActive: "Aktyvūs filtrai: {count}",
    filterNoResults: "Pagal pasirinktus filtrus rezultatų nėra.",
    filterDocPdf: "PDF / Katalogas",
    filterDocDoc: "Gairės",
    filterDocBim: "BIM",
    filterDocCert: "Sertifikatai",
    topBarContact: "Kontaktai",
    topBarSettings: "Techninis centras",
    footerBrand: "Novves sprendimai",
    footerPrivacy: "Privatumas",
    footerStandards: "Standartai",
    footerContact: "Kontaktai",
    solutions: "Sprendimai",
    expertQuote: "Gauti pasiūlymą",
    emptyProducts: "Šio sprendimo komponentų sąrašas dar nepateiktas.",
    emptyDocs: "Atsisiunčiamų dokumentų nėra.",
    docsComingSoon: "Techniniai dokumentai netrukus bus paskelbti techniniame centre.",
    coreComponents: "Pagrindiniai komponentai",
    viewCatalog: "Peržiūrėti visą katalogą",
    moreDetail: "Daugiau",
    addToQuote: "Įtraukti į pasiūlymą",
    added: "Įtraukta",
    documentation: "Dokumentacija",
    selections: "Pasirinkimai",
    projectInquiry: "Projekto užklausa",
    clear: "Išvalyti",
    quote: "Pasiūlymas",
    openMenu: "Atidaryti meniu",
    closeMenu: "Uždaryti meniu",
    sidebarHelp: "Pagalbos centras",
    sidebarTechnicalCenter: "Techninis centras",
    sidebarFireDetection: "Gaisro aptikimas",
    sidebarGasDetection: "Dujų aptikimas",
    sidebarArchive: "Archyvo įrašai",
    docCatalog: "Techninis katalogas 2024",
    docGuidelines: "Projektavimo gairės",
    docBim: "BIM / Revit šeima",
    docCert: "Sertifikatai ir atitiktis",
  },
  pl: {
    categoriesTitle: "Kategorie rozwiązań",
    sidebarSupportTitle: "Wsparcie techniczne",
    sidebarSupportDesc: "Skontaktuj się z naszym zespołem inżynierów w sprawie doboru, montażu i doradztwa projektowego.",
    sidebarSupportCta: "Poproś o wsparcie",
    libraryTitle: "Biblioteka techniczna",
    libraryVersion: "V2.4 ENTERPRISE",
    searchPlaceholder: "Szukaj rozwiązań, produktów lub dokumentów…",
    searchClear: "Wyczyść wyszukiwanie",
    searchNoResults: "Brak wyników dla „{query}”.",
    searchGroupSolutions: "Rozwiązania",
    searchGroupComponents: "Komponenty",
    searchGroupDocuments: "Dokumenty",
    searchResultsHint: "{count} wyników",
    searchMore: "+{count} więcej — zobacz panel boczny",
    searchMinChars: "Wpisz co najmniej 2 znaki",
    filter: "Filtr",
    filterTitle: "Filtruj",
    filterContent: "Zawartość",
    filterContentAll: "Wszystkie",
    filterContentProducts: "Komponenty",
    filterContentDocuments: "Dokumenty",
    filterComponents: "Grupy komponentów",
    filterDocTypes: "Typ dokumentu",
    filterReset: "Resetuj",
    filterActive: "Aktywne filtry: {count}",
    filterNoResults: "Brak wyników dla wybranych filtrów.",
    filterDocPdf: "PDF / Katalog",
    filterDocDoc: "Wytyczne",
    filterDocBim: "BIM",
    filterDocCert: "Certyfikaty",
    topBarContact: "Kontakt",
    topBarSettings: "Centrum techniczne",
    footerBrand: "Novves Solutions",
    footerPrivacy: "Prywatność",
    footerStandards: "Normy",
    footerContact: "Kontakt",
    solutions: "Rozwiązania",
    expertQuote: "Zapytaj o ofertę",
    emptyProducts: "Lista komponentów dla tego rozwiązania nie jest jeszcze dostępna.",
    emptyDocs: "Brak dokumentów do pobrania.",
    docsComingSoon: "Dokumentacja techniczna zostanie wkrótce opublikowana w centrum technicznym.",
    coreComponents: "Podstawowe komponenty",
    viewCatalog: "Zobacz cały katalog",
    moreDetail: "Szczegóły",
    addToQuote: "Dodaj do oferty",
    added: "Dodano",
    documentation: "Dokumentacja",
    selections: "Wybór",
    projectInquiry: "Zapytanie projektowe",
    clear: "Wyczyść",
    quote: "Oferta",
    openMenu: "Otwórz menu",
    closeMenu: "Zamknij menu",
    sidebarHelp: "Centrum pomocy",
    sidebarTechnicalCenter: "Centrum techniczne",
    sidebarFireDetection: "Detekcja pożaru",
    sidebarGasDetection: "Detekcja gazu",
    sidebarArchive: "Zapisy archiwalne",
    docCatalog: "Katalog techniczny 2024",
    docGuidelines: "Wytyczne projektowe",
    docBim: "BIM / Rodzina Revit",
    docCert: "Certyfikaty i zgodność",
  },
  ro: {
    categoriesTitle: "Categorii de soluții",
    sidebarSupportTitle: "Suport tehnic",
    sidebarSupportDesc: "Contactați echipa noastră de ingineri pentru selecție, montaj și consultanță de proiect.",
    sidebarSupportCta: "Solicită suport",
    libraryTitle: "Bibliotecă tehnică",
    libraryVersion: "V2.4 ENTERPRISE",
    searchPlaceholder: "Caută soluții, produse sau documente…",
    searchClear: "Șterge căutarea",
    searchNoResults: "Niciun rezultat pentru „{query}”.",
    searchGroupSolutions: "Soluții",
    searchGroupComponents: "Componente",
    searchGroupDocuments: "Documente",
    searchResultsHint: "{count} rezultate",
    searchMore: "+{count} în plus — vezi bara laterală",
    searchMinChars: "Introduceți cel puțin 2 caractere",
    filter: "Filtru",
    filterTitle: "Filtrează",
    filterContent: "Conținut",
    filterContentAll: "Toate",
    filterContentProducts: "Componente",
    filterContentDocuments: "Documente",
    filterComponents: "Grupuri de componente",
    filterDocTypes: "Tip de document",
    filterReset: "Resetează",
    filterActive: "{count} filtre active",
    filterNoResults: "Niciun rezultat nu corespunde filtrelor selectate.",
    filterDocPdf: "PDF / Catalog",
    filterDocDoc: "Ghiduri",
    filterDocBim: "BIM",
    filterDocCert: "Certificate",
    topBarContact: "Contact",
    topBarSettings: "Centru tehnic",
    footerBrand: "Novves Solutions",
    footerPrivacy: "Confidențialitate",
    footerStandards: "Standarde",
    footerContact: "Contact",
    solutions: "Soluții",
    expertQuote: "Solicită o ofertă",
    emptyProducts: "Lista de componente pentru această soluție nu este încă disponibilă.",
    emptyDocs: "Nu există documente descărcabile disponibile.",
    docsComingSoon: "Documentele tehnice vor fi publicate în curând în centrul tehnic.",
    coreComponents: "Componente principale",
    viewCatalog: "Vezi întregul catalog",
    moreDetail: "Mai multe detalii",
    addToQuote: "Adaugă la ofertă",
    added: "Adăugat",
    documentation: "Documentație",
    selections: "Selecție(i)",
    projectInquiry: "Cerere de proiect",
    clear: "Șterge",
    quote: "Ofertă",
    openMenu: "Deschide meniul",
    closeMenu: "Închide meniul",
    sidebarHelp: "Centru de ajutor",
    sidebarTechnicalCenter: "Centru tehnic",
    sidebarFireDetection: "Detectare incendiu",
    sidebarGasDetection: "Detectare gaze",
    sidebarArchive: "Înregistrări de arhivă",
    docCatalog: "Catalog tehnic 2024",
    docGuidelines: "Ghid de proiectare",
    docBim: "BIM / Familie Revit",
    docCert: "Certificate și conformitate",
  },
  hu: {
    categoriesTitle: "Megoldási kategóriák",
    sidebarSupportTitle: "Műszaki támogatás",
    sidebarSupportDesc: "Vegye fel a kapcsolatot mérnöki csapatunkkal kiválasztás, beépítés és projekt-tanácsadás ügyében.",
    sidebarSupportCta: "Támogatás kérése",
    libraryTitle: "Műszaki könyvtár",
    libraryVersion: "V2.4 ENTERPRISE",
    searchPlaceholder: "Megoldások, termékek vagy dokumentumok keresése…",
    searchClear: "Keresés törlése",
    searchNoResults: "Nincs találat a következőre: „{query}”.",
    searchGroupSolutions: "Megoldások",
    searchGroupComponents: "Komponensek",
    searchGroupDocuments: "Dokumentumok",
    searchResultsHint: "{count} találat",
    searchMore: "+{count} további — lásd az oldalsávot",
    searchMinChars: "Írjon be legalább 2 karaktert",
    filter: "Szűrő",
    filterTitle: "Szűrés",
    filterContent: "Tartalom",
    filterContentAll: "Összes",
    filterContentProducts: "Komponensek",
    filterContentDocuments: "Dokumentumok",
    filterComponents: "Komponenscsoportok",
    filterDocTypes: "Dokumentumtípus",
    filterReset: "Visszaállítás",
    filterActive: "{count} aktív szűrő",
    filterNoResults: "Nincs a kiválasztott szűrőknek megfelelő találat.",
    filterDocPdf: "PDF / Katalógus",
    filterDocDoc: "Irányelvek",
    filterDocBim: "BIM",
    filterDocCert: "Tanúsítványok",
    topBarContact: "Kapcsolat",
    topBarSettings: "Műszaki központ",
    footerBrand: "Novves Solutions",
    footerPrivacy: "Adatvédelem",
    footerStandards: "Szabványok",
    footerContact: "Kapcsolat",
    solutions: "Megoldások",
    expertQuote: "Ajánlatkérés",
    emptyProducts: "Ehhez a megoldáshoz még nem érhető el a komponenslista.",
    emptyDocs: "Nincs letölthető dokumentum.",
    docsComingSoon: "A műszaki dokumentumok hamarosan megjelennek a műszaki központban.",
    coreComponents: "Alapkomponensek",
    viewCatalog: "Teljes katalógus megtekintése",
    moreDetail: "További részletek",
    addToQuote: "Hozzáadás az ajánlathoz",
    added: "Hozzáadva",
    documentation: "Dokumentáció",
    selections: "Kiválasztás(ok)",
    projectInquiry: "Projektmegkeresés",
    clear: "Törlés",
    quote: "Ajánlat",
    openMenu: "Menü megnyitása",
    closeMenu: "Menü bezárása",
    sidebarHelp: "Súgóközpont",
    sidebarTechnicalCenter: "Műszaki központ",
    sidebarFireDetection: "Tűzérzékelés",
    sidebarGasDetection: "Gázérzékelés",
    sidebarArchive: "Archív bejegyzések",
    docCatalog: "Műszaki katalógus 2024",
    docGuidelines: "Tervezési irányelvek",
    docBim: "BIM / Revit család",
    docCert: "Tanúsítványok és megfelelőség",
  },
};

export function solutionLibraryUi(locale: string): SolutionLibraryUi {
  return UI[locale as Locale] ?? UI.en;
}
